import assert from 'node:assert/strict'
import {createBetaStore,createBetaSession,addBetaSession,finishBetaSession,addFeedback,addDefect,transitionDefect,createHomologationChecklist,evaluateHomologation,signHomologation,betaSummary,BETA_SEVERITY} from '../src/editor-core/beta-homologation.js'
const tests=[]; const t=(n,f)=>tests.push([n,f])
t('severity vocabulary',()=>assert.deepEqual(BETA_SEVERITY,['BLOCKER','CRITICAL','MAJOR','MINOR','COSMETIC']))
t('creates store',()=>assert.equal(createBetaStore().sessions.length,0))
t('creates corporate beta session',()=>assert.equal(createBetaSession({id:'s1',participant:'u1',role:'Inspetor',scenario:'Editor'}).environment,'CORPORATE_BETA'))
t('adds session',()=>{const s=createBetaStore();addBetaSession(s,createBetaSession({id:'s1',participant:'u',role:'r',scenario:'x'}));assert.equal(s.sessions.length,1)})
t('finishes session',()=>{const s=createBetaStore();addBetaSession(s,createBetaSession({id:'s1',participant:'u',role:'r',scenario:'x'}));assert.equal(finishBetaSession(s,'s1',{result:'PASS'}).status,'FINISHED')})
t('feedback requires session',()=>assert.throws(()=>addFeedback(createBetaStore(),{id:'f',sessionId:'x',category:'UX',message:'m'})))
t('records feedback',()=>{const s=createBetaStore();addBetaSession(s,createBetaSession({id:'s',participant:'u',role:'r',scenario:'x'}));addFeedback(s,{id:'f',sessionId:'s',category:'UX',message:'ok'});assert.equal(s.feedback.length,1)})
t('rejects invalid severity',()=>assert.throws(()=>addDefect(createBetaStore(),{id:'d',title:'x',severity:'BAD',area:'UI'})))
t('records defect',()=>assert.equal(addDefect(createBetaStore(),{id:'d',title:'x',area:'UI'}).status,'OPEN'))
t('transitions defect',()=>{const s=createBetaStore();addDefect(s,{id:'d',title:'x',area:'UI'});assert.equal(transitionDefect(s,'d','VERIFIED').status,'VERIFIED')})
t('checklist created',()=>assert.equal(createHomologationChecklist([{area:'Editor',criterion:'drag'}]).length,1))
t('pending environment blocks approval without rejection',()=>{const c=createHomologationChecklist([{area:'E2E',criterion:'browser',status:'PENDING_ENVIRONMENT'}]);const r=evaluateHomologation({checklist:c});assert.equal(r.status,'PENDING_ENVIRONMENT')})
t('critical open rejects',()=>{const c=createHomologationChecklist([{area:'Core',criterion:'tests',status:'APPROVED'}]);const r=evaluateHomologation({checklist:c,defects:[{severity:'CRITICAL',status:'OPEN'}]});assert.equal(r.status,'REJECTED')})
t('verified critical no longer blocks',()=>{const c=createHomologationChecklist([{area:'Core',criterion:'tests',status:'APPROVED'}]);assert.equal(evaluateHomologation({checklist:c,defects:[{severity:'CRITICAL',status:'VERIFIED'}]}).approved,true)})
t('explicit rejection rejects',()=>assert.equal(evaluateHomologation({checklist:createHomologationChecklist([{area:'UX',criterion:'quality',status:'REJECTED'}])}).status,'REJECTED'))
t('all approved passes',()=>assert.equal(evaluateHomologation({checklist:createHomologationChecklist([{area:'Core',criterion:'tests',status:'APPROVED'}])}).approved,true))
t('signoff immutable',()=>{const s=createBetaStore();const x=signHomologation(s,{id:'h',actor:'A',role:'QA',status:'PENDING_ENVIRONMENT',scope:'Beta'});assert.equal(Object.isFrozen(x),true)})
t('events appended',()=>{const s=createBetaStore();addDefect(s,{id:'d',title:'x',area:'UI'});assert.equal(s.events.length,1)})
t('summary counts critical',()=>{const s=createBetaStore();addDefect(s,{id:'d',title:'x',area:'UI',severity:'CRITICAL'});assert.equal(betaSummary(s).openCritical,1)})
let pass=0; for(const [n,f] of tests){try{f();pass++;console.log(`PASS ${n}`)}catch(e){console.error(`FAIL ${n}`,e);process.exitCode=1}} console.log(`Beta/Homologation Core: ${pass}/${tests.length} PASS`)
