import assert from'node:assert/strict';
import{createPipeRun,movePipeRun}from'../src/editor-core/piping.js';
import{DIMENSION_TYPES,freeAnchor,entityAnchor,resolveAnchor,createDimension,resolveDimension,updateDimension,createElevation,resolveElevation,createIndustrialCoordinate,resolveIndustrialCoordinate,createFlowArrow,resolveFlowArrow,reverseFlowArrow,createNorthArrow,rotateNorthArrow,validateDocumentationEntity}from'../src/editor-core/documentation.js';
let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
const run=createPipeRun('P1',[{x:0,y:0},{x:100,y:0},{x:100,y:100}],{lineNumber:'4-P-001'});
t('all required dimension types exist',()=>assert.deepEqual(DIMENSION_TYPES,['linear','aligned','horizontal','vertical','angular','between-points','offset','elevation']));
t('free anchor resolves',()=>assert.deepEqual(resolveAnchor(freeAnchor({x:4,y:8}),[run]),{x:4,y:8}));
t('pipe vertex anchor resolves',()=>assert.deepEqual(resolveAnchor(entityAnchor('P1',{kind:'vertex',index:1}),[run]),{x:100,y:0}));
t('pipe segment anchor resolves by t',()=>assert.deepEqual(resolveAnchor(entityAnchor('P1',{kind:'segment',index:1,t:.25}),[run]),{x:100,y:25}));
const d=createDimension('D1','aligned',entityAnchor('P1',{kind:'vertex',index:0}),entityAnchor('P1',{kind:'vertex',index:1}),{engineeringValue:2850,unit:'mm'}),rd=resolveDimension(d,[run]);
t('dimension resolves associated anchors',()=>assert.equal(rd.resolved,true));
t('dimension keeps graphic distance separate',()=>assert.equal(rd.graphicDistance,100));
t('dimension engineering value is independent',()=>assert.equal(rd.engineeringValue,2850));
t('dimension label uses engineering value',()=>assert.equal(rd.label,'2850 mm'));
const undef=resolveDimension(createDimension('D2','horizontal',freeAnchor({x:0,y:0}),freeAnchor({x:150,y:0})),[]);
t('undefined physical dimension is not inferred from drawing',()=>{assert.equal(undef.graphicMeasurement,150);assert.equal(undef.engineeringValue,null);assert.equal(undef.label,'DIMENSÃO NÃO DEFINIDA')});
t('dimension engineering value can be edited',()=>assert.equal(updateDimension(d,{engineeringValue:3100}).engineeringValue,3100));
const moved=movePipeRun(run,25,40),rd2=resolveDimension(d,[moved]);
t('associative dimension follows moved pipe',()=>{assert.deepEqual(rd2.a,{x:25,y:40});assert.deepEqual(rd2.b,{x:125,y:40});assert.equal(rd2.engineeringValue,2850)});
const el=createElevation('EL1',entityAnchor('P1',{kind:'segment',index:1,t:.5}),{elevation:12340,datum:'DATUM A'}),rel=resolveElevation(el,[run]);
t('elevation associates to pipe',()=>assert.deepEqual(rel.point,{x:100,y:50}));
t('elevation label is dedicated EL object',()=>assert.equal(rel.label,'EL. 12340 mm'));
const sym={id:'V1',kind:'industrial-symbol',x:20,y:30,width:60,height:40,ports:[{id:'P1',x:0,y:20}]};
const elc=resolveElevation(createElevation('EL2',entityAnchor('V1',{kind:'center'}),{elevation:5000}),[sym]);
t('elevation associates to component center',()=>assert.deepEqual(elc.point,{x:50,y:50}));
const coord=createIndustrialCoordinate('C1',entityAnchor('P1',{kind:'vertex',index:2}),{n:123.4,e:456.7,x:1,y:2,z:3,datum:'D-01',reference:'PONTO A'}),rc=resolveIndustrialCoordinate(coord,[run]);
t('industrial coordinate resolves anchor',()=>assert.deepEqual(rc.point,{x:100,y:100}));
t('industrial coordinate stores N E X Y Z datum reference',()=>{assert.equal(coord.n,123.4);assert.equal(coord.e,456.7);assert.equal(coord.xCoord,1);assert.equal(coord.yCoord,2);assert.equal(coord.z,3);assert.equal(coord.datum,'D-01');assert.equal(coord.reference,'PONTO A')});
t('industrial coordinate is explicitly separate from GPS',()=>{assert.equal(coord.coordinateSystem,'INDUSTRIAL');assert.equal('lat'in coord,false);assert.equal('lon'in coord,false)});
const flow=createFlowArrow('F1','P1',0,{t:.5}),rf=resolveFlowArrow(flow,[run]);
t('flow arrow associates to pipe segment',()=>{assert.deepEqual(rf.point,{x:50,y:0});assert.equal(rf.angle,0)});
const rfm=resolveFlowArrow(flow,[moved]);
t('flow arrow follows moved pipe',()=>assert.deepEqual(rfm.point,{x:75,y:40}));
t('flow direction can reverse',()=>assert.equal(resolveFlowArrow(reverseFlowArrow(flow),[run]).angle,180));
const north=createNorthArrow('N1',{sheetId:'SHEET-1',x:70,y:60,rotation:30});
t('north arrow is associated to sheet',()=>{assert.equal(north.associatedToSheet,true);assert.equal(north.sheetId,'SHEET-1')});
t('north arrow is rotatable',()=>assert.equal(rotateNorthArrow(north,75).rotation,75));
t('dimension validation reports undefined engineering value as info',()=>{const v=validateDocumentationEntity(createDimension('D3','linear',freeAnchor({x:0,y:0}),freeAnchor({x:10,y:0})),[]);assert.equal(v.valid,true);assert.equal(v.issues[0].code,'ENGINEERING_DIMENSION_UNDEFINED')});
t('broken association is warning not crash',()=>{const v=validateDocumentationEntity(createElevation('E3',entityAnchor('MISSING'),{}),[]);assert.equal(v.valid,true);assert.equal(v.issues[0].code,'BROKEN_ASSOCIATION')});
console.log(`DOCUMENTATION ${n}/24 PASS`);
