import assert from'node:assert/strict';
import{createPipeRun,addPipeWaypointProjected,removePipeWaypoint,updatePipeEngineering}from'../src/editor-core/piping.js';
import{createEngineeringGraph,registerPipeRun,syncPipeRun,unregisterPipeRun,connectPorts,disconnectConnection,connectedComponent,areNodesConnected,graphStats,validateEngineeringGraph}from'../src/editor-core/engineering-graph.js';
import{segmentIntersection,detectPipeCrossings,nearestPipeSegment,topologyDiagnostics}from'../src/editor-core/topology.js';
let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
const a=createPipeRun('A',[{x:0,y:0},{x:100,y:0},{x:200,y:0}],{lineNumber:'A',nominalSize:'4"',spec:'C1'});
const b=createPipeRun('B',[{x:200,y:0},{x:200,y:100}],{lineNumber:'B',nominalSize:'4"',spec:'C1'});
let g=createEngineeringGraph();
t('empty graph',()=>assert.deepEqual(graphStats(g),{runs:0,nodes:0,ports:0,pipeEdges:0,connections:0,attachments:0}));
g=registerPipeRun(g,a);g=registerPipeRun(g,b);
t('register creates engineering topology',()=>assert.deepEqual(graphStats(g),{runs:2,nodes:5,ports:4,pipeEdges:3,connections:0,attachments:0}));
t('scene coordinates absent from engineering nodes',()=>assert.equal('x'in g.nodes['A-V001'],false));
t('run engineering metadata persisted',()=>assert.equal(g.runs.A.engineering.lineNumber,'A'));
t('internal run is connected',()=>assert.ok(areNodesConnected(g,'A-V001','A-V003')));
t('separate runs are not auto-connected by coincident coordinates',()=>assert.equal(areNodesConnected(g,'A-V001','B-V001'),false));
g=connectPorts(g,'A-PORT-END','B-PORT-START');
t('explicit port connection joins topology',()=>{assert.ok(areNodesConnected(g,'A-V001','B-V002'));assert.equal(graphStats(g).connections,1)});
t('connected component traverses pipe edges and explicit connection',()=>assert.equal(connectedComponent(g,'A-V001').length,5));
t('graph validates with unused ports as info only',()=>{const v=validateEngineeringGraph(g);assert.equal(v.valid,true);assert.ok(v.issues.some(i=>i.code==='PORT_UNUSED'))});
const cid=Object.keys(g.connections)[0];const aEndpointChanged=removePipeWaypoint(a,0);let gc=createEngineeringGraph();gc=registerPipeRun(gc,a);gc=registerPipeRun(gc,b);gc=connectPorts(gc,'A-PORT-START','B-PORT-END');gc=syncPipeRun(gc,aEndpointChanged);
t('connected endpoint follows stable port after vertex change',()=>{const c=Object.values(gc.connections)[0];assert.equal(c.source,'A-V002');assert.ok(validateEngineeringGraph(gc).valid)});
g=disconnectConnection(g,cid);
t('disconnect separates runs',()=>assert.equal(areNodesConnected(g,'A-V001','B-V002'),false));
const a2=addPipeWaypointProjected(a,0,{x:50,y:20});g=syncPipeRun(g,a2);
t('sync follows semantic split',()=>{assert.equal(g.runs.A.edgeIds.length,3);assert.ok(g.edges['A-S003']);assert.ok(validateEngineeringGraph(g).valid)});
const a3=updatePipeEngineering(a2,{service:'Água'});g=syncPipeRun(g,a3);
t('sync engineering properties',()=>assert.equal(g.runs.A.engineering.service,'Água'));
t('segment intersection geometry',()=>{const h=segmentIntersection({x:0,y:0},{x:100,y:100},{x:0,y:100},{x:100,y:0});assert.deepEqual(h.point,{x:50,y:50})});
const c=createPipeRun('C',[{x:0,y:50},{x:100,y:50}],{lineNumber:'C'}),d=createPipeRun('D',[{x:50,y:0},{x:50,y:100}],{lineNumber:'D'});
t('crossing detection does not create connection',()=>{const xs=detectPipeCrossings([c,d]);assert.equal(xs.length,1);assert.equal(xs[0].createsConnection,false)});
t('nearest semantic segment',()=>{const h=nearestPipeSegment([a],{x:30,y:4});assert.equal(h.runId,'A');assert.equal(h.segmentId,'A-S001')});
t('diagnostics flags scene/graph divergence and crossings',()=>{const q=topologyDiagnostics(createEngineeringGraph(),[c,d]);assert.ok(q.some(i=>i.code==='SCENE_RUN_WITHOUT_GRAPH'));assert.ok(q.some(i=>i.code==='GRAPHIC_CROSSING_NOT_CONNECTED'))});
g=unregisterPipeRun(g,'B');
t('unregister removes run topology',()=>{assert.equal(g.runs.B,undefined);assert.equal(g.nodes['B-V001'],undefined)});
console.log(`ENGINEERING_GRAPH ${n}/18 PASS`);
