import assert from 'node:assert/strict';
import {createEvidenceStore,createEvidence,addEvidence,createPhotoOverlay,addPhotoOverlay,compareEvidence,createAnomaly,addAnomaly,createRecommendation,addRecommendation,transitionRecommendation,closeAnomaly,evidenceStats,validateEvidenceStore} from '../src/editor-core/evidence-integrity.js';
let n=0; const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
let s=createEvidenceStore();
const p1=createEvidence({id:'E1',kind:'PHOTO',target:{kind:'tml',id:'T1'},name:'antes.jpg',date:'2026-01-01',author:'inspetor'});s=addEvidence(s,p1,'u1');
t('evidence target preserved',()=>assert.equal(s.evidence[0].target.id,'T1'));
t('original immutable flag',()=>assert.equal(s.evidence[0].originalImmutable,true));
s=addPhotoOverlay(s,createPhotoOverlay({id:'O1',evidenceId:'E1',shapes:[{kind:'arrow',x:1,y:2}]}),'u1');
t('photo overlay non destructive',()=>assert.equal(s.photoOverlays[0].nonDestructive,true));
t('original unchanged by overlay',()=>assert.equal(s.evidence[0].name,'antes.jpg'));
s=addEvidence(s,createEvidence({id:'E2',kind:'PHOTO',target:{kind:'tml',id:'T1'},name:'depois.jpg',date:'2026-01-11'}));
t('comparison same target',()=>assert.equal(compareEvidence(s,'E1','E2').sameTarget,true));
t('comparison days',()=>assert.equal(compareEvidence(s,'E1','E2').daysApart,10));
const a=createAnomaly({id:'A1',target:{kind:'tml',id:'T1'},description:'Perda localizada',location:'6h',classification:'LOSS',evidenceIds:['E1']});s=addAnomaly(s,a,'u1');
t('anomaly linked evidence',()=>assert.deepEqual(s.anomalies[0].evidenceIds,['E1']));
let threw=false;try{addAnomaly(s,createAnomaly({target:{kind:'tml',id:'T1'},description:'x',evidenceIds:['NO']}))}catch{threw=true}t('reject missing evidence',()=>assert.equal(threw,true));
s=addRecommendation(s,createRecommendation({id:'R1',anomalyId:'A1',description:'Inspecionar área'}),'u1');
t('recommendation linked anomaly',()=>assert.equal(s.recommendations[0].anomalyId,'A1'));
s=transitionRecommendation(s,'R1','PLANNED',{actor:'u1'});s=transitionRecommendation(s,'R1','EXECUTED',{actor:'u1'});t('execution timestamp',()=>assert.ok(s.recommendations[0].executedAt));
let blocked=false;try{closeAnomaly(s,'A1')}catch{blocked=true}t('cannot close before verification',()=>assert.equal(blocked,true));
s=transitionRecommendation(s,'R1','VERIFIED',{actor:'u2',note:'Conferido'});t('verification separate step',()=>assert.equal(s.recommendations[0].verificationNote,'Conferido'));
s=closeAnomaly(s,'A1',{actor:'u2'});t('close after verification',()=>assert.equal(s.anomalies[0].status,'CLOSED'));
t('append-only event trail',()=>assert.ok(s.events.length>=7));
t('stats',()=>assert.deepEqual(evidenceStats(s),{evidence:2,photos:2,anomalies:1,openAnomalies:0,recommendations:1,pendingVerification:0}));
t('validation clean',()=>assert.deepEqual(validateEvidenceStore(s),[]));
console.log(`evidence-integrity ${n}/${n}`);
