import assert from'node:assert/strict';import{createDoubtQueue,doubtFromSymbolDetection,doubtFromOcr,createCrossingDoubt,enqueueDoubt,doubtSummary,resolveDoubt,markUnknown,ignoreDoubt,reopenDoubt,navigateDoubt,focusTargets,applyResolutionToRecognition,canPromoteToEngineeringFact}from'../src/editor-core/human-in-loop.js';
let n=0;const ok=(name,fn)=>{fn();n++;console.log(`PASS ${n}: ${name}`)};
const det={id:'SD-1',bbox:{x:1,y:2,width:30,height:20},confidence:.64,symbolId:'valve-gate',alternatives:[{symbolId:'valve-gate',name:'Gaveta',confidence:.64},{symbolId:'valve-globe',name:'Globo',confidence:.61}]};
const sd=doubtFromSymbolDetection(det);ok('symbol doubt preserves crop/confidence/alternatives',()=>{assert.equal(sd.type,'SYMBOL');assert.equal(sd.alternatives.length,2);assert.deepEqual(sd.crop,det.bbox)});
const od=doubtFromOcr({id:'OCR-1',text:'4-P-0451?',confidence:.72,bbox:{x:4,y:5,width:80,height:12},alternatives:['4-P-04517','4-P-04512']});ok('OCR ambiguity supports editable alternatives',()=>assert.equal(od.hypothesis,'4-P-0451?'));
const cd=createCrossingDoubt({id:'Q-X',bbox:{x:9,y:9,width:8,height:8},lineIds:['A','B']});ok('crossing question has connected/crossing/unknown',()=>assert.deepEqual(cd.alternatives.map(x=>x.value),['CONNECTED','CROSSING_ONLY','UNKNOWN']));
let q=createDoubtQueue();q=enqueueDoubt(q,sd);q=enqueueDoubt(q,od);q=enqueueDoubt(q,cd);ok('summary pending',()=>assert.deepEqual(doubtSummary(q),{total:3,resolved:0,pending:3,ignored:0}));
ok('deduplicates ids',()=>assert.equal(enqueueDoubt(q,sd).items.length,3));
q=resolveDoubt(q,sd.id,'valve-globe',{userId:'inspetor'});ok('resolve is auditable',()=>{const x=q.items[0];assert.equal(x.status,'RESOLVED');assert.equal(x.resolution.userId,'inspetor')});
ok('resolved known may promote',()=>assert.equal(canPromoteToEngineeringFact(q.items[0]),true));
q=markUnknown(q,od.id);ok('unknown never promotes',()=>assert.equal(canPromoteToEngineeringFact(q.items[1]),false));
q=ignoreDoubt(q,cd.id,{reason:'fora do escopo'});ok('ignore tracked',()=>assert.equal(q.items[2].status,'IGNORED'));
q=reopenDoubt(q,cd.id);ok('reopen returns pending',()=>assert.equal(q.items[2].status,'PENDING'));
const q2=navigateDoubt({...q,activeId:sd.id},1);ok('next navigation',()=>assert.equal(q2.activeId,od.id));
const q3=navigateDoubt(q2,-1);ok('previous navigation',()=>assert.equal(q3.activeId,sd.id));
ok('focus returns original and digital targets',()=>{const f=focusTargets(sd);assert.deepEqual(f.original,det.bbox);assert.equal(f.digital.id,'SD-1')});
const applied=applyResolutionToRecognition(det,q.items[0]);ok('human answer confirms recognition',()=>{assert.equal(applied.symbolId,'valve-globe');assert.equal(applied.confirmedBy,'HUMAN')});
const unk=applyResolutionToRecognition(det,q.items[1]);ok('unknown leaves proposal unconfirmed',()=>assert.equal(unk.confirmed,false));
ok('summary mixed states',()=>assert.deepEqual(doubtSummary(q),{total:3,resolved:2,pending:1,ignored:0}));
console.log(`Human-in-loop Core: ${n}/${n} PASS`);
