import assert from'node:assert/strict';
import{createPipeRun,updatePipeSegment}from'../src/editor-core/piping.js';
import{createEngineeringGraph,registerPipeRun,connectPorts,areNodesConnected,validateEngineeringGraph}from'../src/editor-core/engineering-graph.js';
import{getSymbol,defaultSymbolPorts}from'../src/editor-core/library.js';
import{isInlineSymbol,isTeeSymbol,splitPipeRunForInline,insertInlineComponentTransaction,insertTeeBranchTransaction}from'../src/editor-core/inline-components.js';
let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
const valve=getSymbol('valve-gate'),tee=getSymbol('tee');
t('valve is inline eligible',()=>assert.equal(isInlineSymbol(valve),true));
t('tee classified separately',()=>{assert.equal(isTeeSymbol(tee),true);assert.equal(isInlineSymbol(tee),false)});
t('tee exposes three scene ports',()=>assert.equal(defaultSymbolPorts(tee,72,46).length,3));
let run=createPipeRun('MAIN',[{x:0,y:0},{x:100,y:0},{x:200,y:0}],{lineNumber:'6"-P-100',nominalSize:'6"',spec:'BC05'});
run=updatePipeSegment(run,'MAIN-S001',{physicalLength:2500,properties:{weldMap:'W1'}});
const split=splitPipeRunForInline(run,0,{x:40,y:9},{leftRunId:'MAIN-A',rightRunId:'MAIN-B'});
t('split projects insertion to source segment',()=>assert.deepEqual(split.point,{x:40,y:0}));
t('split preserves main engineering metadata',()=>{assert.equal(split.left.engineering.lineNumber,'6"-P-100');assert.equal(split.right.engineering.spec,'BC05')});
t('split does not invent physical lengths',()=>{assert.equal(split.left.segments.at(-1).physicalLength,null);assert.equal(split.right.segments[0].physicalLength,null)});
t('split records source segment provenance',()=>assert.equal(split.left.segments.at(-1).properties.splitFromSegmentId,'MAIN-S001'));
let g=createEngineeringGraph();g=registerPipeRun(g,run);
const state={entities:[run],graph:g};
const tx=insertInlineComponentTransaction(state,{runId:'MAIN',segmentIndex:0,point:{x:50,y:5},symbol:valve,componentId:'V-001',leftRunId:'MAIN-L',rightRunId:'MAIN-R'});
t('inline transaction succeeds',()=>assert.equal(tx.ok,true));
t('original run replaced atomically by two runs and component',()=>{assert.equal(tx.entities.some(e=>e.id==='MAIN'),false);assert.ok(tx.entities.some(e=>e.id==='MAIN-L'));assert.ok(tx.entities.some(e=>e.id==='MAIN-R'));assert.ok(tx.entities.some(e=>e.id==='V-001'))});
t('engineering component registered',()=>assert.equal(tx.graph.components['V-001'].portIds.length,2));
t('inline topology creates two explicit connections',()=>assert.equal(Object.keys(tx.graph.connections).length,2));
t('topology traverses through inline component',()=>assert.ok(areNodesConnected(tx.graph,'MAIN-L-V001','MAIN-R-V002')));
t('inline graph validates',()=>assert.equal(validateEngineeringGraph(tx.graph).valid,true));
t('transaction audit marks atomic operation',()=>assert.deepEqual(tx.transaction.type,'INSERT_INLINE_COMPONENT'));
const bad=insertInlineComponentTransaction(state,{runId:'MAIN',segmentIndex:0,point:{x:0,y:0},symbol:valve,componentId:'BAD'});
t('invalid endpoint insertion rolls back',()=>{assert.equal(bad.ok,false);assert.equal(bad.rolledBack,true);assert.strictEqual(bad.entities,state.entities);assert.strictEqual(bad.graph,state.graph)});
const teeTx=insertTeeBranchTransaction(state,{runId:'MAIN',segmentIndex:1,point:{x:150,y:0},symbol:tee,componentId:'TEE-001',leftRunId:'M-L',rightRunId:'M-R',branchRunId:'M-BR',branchEnd:{x:150,y:-120},branchEngineering:{nominalSize:'3"'}});
t('tee transaction succeeds',()=>assert.equal(teeTx.ok,true));
t('tee creates third branch run',()=>{assert.ok(teeTx.entities.some(e=>e.id==='M-BR'));assert.equal(teeTx.graph.components['TEE-001'].portIds.length,3)});
t('tee creates three explicit connections',()=>assert.equal(Object.keys(teeTx.graph.connections).length,3));
t('branch may override diameter while preserving line number',()=>{const br=teeTx.entities.find(e=>e.id==='M-BR');assert.equal(br.engineering.nominalSize,'3"');assert.equal(br.engineering.lineNumber,'6"-P-100')});
t('main and branch are topologically connected through tee',()=>assert.ok(areNodesConnected(teeTx.graph,'M-L-V001','M-BR-V002')));
t('tee graph validates',()=>assert.equal(validateEngineeringGraph(teeTx.graph).valid,true));
// Existing external connection preservation
const ext=createPipeRun('EXT',[{x:-100,y:0},{x:0,y:0}],{lineNumber:'EXT'});let gx=createEngineeringGraph();gx=registerPipeRun(gx,run);gx=registerPipeRun(gx,ext);gx=connectPorts(gx,'EXT-PORT-END','MAIN-PORT-START');
const preserve=insertInlineComponentTransaction({entities:[run,ext],graph:gx},{runId:'MAIN',segmentIndex:1,point:{x:150,y:0},symbol:valve,componentId:'V-002',leftRunId:'P-L',rightRunId:'P-R'});
t('existing external endpoint connection is preserved',()=>assert.ok(areNodesConnected(preserve.graph,'EXT-V001','P-L-V001')));
console.log(`INLINE_COMPONENTS ${n}/22 PASS`);
