import assert from'node:assert/strict'; import{createNativePackage,validateNativePackage,migrateDocument,importPlan,exportPlan,createPrintSettings,createReportModel,reportToCsv,svgExportModel,IMPORT_FORMATS,EXPORT_FORMATS}from'../src/editor-core/io-reporting.js';
let n=0;const t=async(name,fn)=>{await fn();n++;console.log('PASS',name)};
await t('native package structured',async()=>{let p=await createNativePackage({id:'D1'});assert.equal(p.manifest.format,'h2fiso');assert.ok(p.manifest.documentSha256)});
await t('native validates',async()=>assert.equal(validateNativePackage(await createNativePackage({id:'D'})),true));
await t('native rejects invalid',()=>assert.throws(()=>validateNativePackage({})));await t('schema migration',()=>assert.equal(migrateDocument({id:'D'},'1.0').schemaVersion,'2.0.0'));
await t('all import formats',()=>assert.equal(IMPORT_FORMATS.length,7));await t('h2f native import',()=>assert.equal(importPlan('h2fiso').editableDirectly,true));await t('pdf analysis import',()=>assert.equal(importPlan('pdf').mode,'UNDERLAY_OR_ANALYSIS'));await t('dxf vector interop',()=>assert.equal(importPlan('dxf').mode,'VECTOR_INTEROP'));
await t('all export formats',()=>assert.equal(EXPORT_FORMATS.length,6));await t('pdf vector preferred',()=>assert.equal(exportPlan('pdf').vectorPreferred,true));await t('pdf preserves primitives',()=>assert.ok(exportPlan('pdf').preserve.includes('titleBlock')));await t('print preview',()=>assert.equal(createPrintSettings().preview,true));await t('all sheets print',()=>assert.equal(createPrintSettings({area:'ALL_SHEETS'}).area,'ALL_SHEETS'));await t('invalid print rejected',()=>assert.throws(()=>createPrintSettings({orientation:'X'})));
await t('report aggregates domains',()=>{let r=createReportModel({document:{id:'D',sheets:[{}]},inspection:{tmls:[{}],ndt:[{}]},evidence:{anomalies:[{}]}});assert.equal(r.sections.inspection.tml,1);assert.equal(r.sections.evidence.anomalies,1)});await t('csv generated',()=>assert.match(reportToCsv(createReportModel({})),/section/));await t('svg model vector',()=>assert.equal(svgExportModel({entities:[{}]}).vector,true));
console.log(`IO/Reporting Core: ${n}/${n} PASS`);
