import assert from'node:assert/strict';
import{LIBRARY_CATEGORIES,BUILTIN_SYMBOLS,LIBRARY_SCOPES,SYMBOL_PRIMITIVES,validateLibrary,searchLibrary,toggleFavorite,pushRecent,createSymbolEntity,createSymbolEntityFrom,libraryStats,createCustomSymbol,addSymbolPrimitive,addCustomConnectionPoint,versionCustomSymbol,exportCustomLibrary,importCustomLibrary}from'../src/editor-core/library.js';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS',name)};
test('11 categorias obrigatórias',()=>assert.equal(LIBRARY_CATEGORIES.length,11));
test('biblioteca válida e IDs únicos',()=>assert.equal(validateLibrary().valid,true));
test('86 símbolos built-in',()=>assert.equal(BUILTIN_SYMBOLS.length,86));
const must=(cat,names)=>test(`${cat} contém catálogo mínimo`,()=>{const ids=new Set(BUILTIN_SYMBOLS.filter(s=>s.category===cat).map(s=>s.id));for(const id of names)assert.ok(ids.has(id),id)});
must('VÁLVULAS',['valve-gate','valve-globe','valve-ball','valve-butterfly','valve-check','valve-needle','valve-plug','valve-diaphragm','valve-control','valve-safety','valve-relief','valve-generic']);
must('CONEXÕES',['elbow-90','elbow-45','tee','lateral','cross','coupling','union','cap','plug','reducer','weldolet','sockolet','threadolet','olet-generic']);
must('FLANGES',['flange-wn','flange-so','flange-sw','flange-lj','flange-blind','flange-threaded','flange-pair']);
must('SUPORTES',['support-rest','support-guide','support-anchor','support-shoe','support-hanger','support-spring','support-generic','support-special']);
must('INSTRUMENTAÇÃO',['inst-pi','inst-pt','inst-ti','inst-tt','inst-fi','inst-ft','inst-li','inst-lt','inst-generic','inst-local','inst-transmitter']);
must('EQUIPAMENTOS',['equip-vessel','equip-tank','equip-pump','equip-compressor','equip-exchanger','equip-column','equip-furnace','equip-filter','equip-reactor','equip-generic','equip-nozzle']);
test('busca ignora acentos e encontra nome',()=>assert.ok(searchLibrary(BUILTIN_SYMBOLS,{query:'valvula esfera'}).some(s=>s.id==='valve-ball')));
test('busca por sigla',()=>assert.ok(searchLibrary(BUILTIN_SYMBOLS,{query:'PSV'}).some(s=>s.id==='valve-safety')));
test('filtro por categoria',()=>assert.ok(searchLibrary(BUILTIN_SYMBOLS,{category:'END'}).every(s=>s.category==='END')));
test('favoritos determinísticos',()=>{let f=toggleFavorite([],'valve-ball');assert.deepEqual(f,['valve-ball']);f=toggleFavorite(f,'valve-ball');assert.deepEqual(f,[])});
test('recentes sem duplicação e limitados',()=>{let r=[];for(let i=0;i<20;i++)r=pushRecent(r,BUILTIN_SYMBOLS[i].id,12);assert.equal(r.length,12);r=pushRecent(r,r[4],12);assert.equal(new Set(r).size,r.length)});
test('entidade industrial preserva metadados',()=>{const e=createSymbolEntity('valve-gate',{x:100,y:200},{id:'SYM-001'});assert.equal(e.kind,'industrial-symbol');assert.equal(e.symbolId,'valve-gate');assert.equal(e.ports.length,2);assert.equal(e.x,64);assert.equal(e.y,177)});
test('instrumento não inventa process ports',()=>assert.equal(createSymbolEntity('inst-pi',{x:0,y:0}).ports.length,0));
test('estatística fecha total',()=>{const st=libraryStats();assert.equal(Object.values(st.byCategory).reduce((a,b)=>a+b,0),st.symbols)});
test('escopos customizados obrigatórios',()=>assert.deepEqual(LIBRARY_SCOPES,['CORPORATE','TENANT','PROJECT','USER']));
test('8 primitivas do editor',()=>assert.deepEqual(SYMBOL_PRIMITIVES,['line','polyline','arc','circle','ellipse','rectangle','polygon','text']));
test('símbolo customizado aceita primitivas e connection points',()=>{let s=createCustomSymbol({id:'custom-a',name:'Custom A',scope:'PROJECT'});s=addSymbolPrimitive(s,{type:'circle',cx:36,cy:23,r:10});s=addCustomConnectionPoint(s,{x:0,y:23});assert.equal(s.primitives.length,1);assert.equal(s.connectionPoints.length,1);assert.equal(createSymbolEntityFrom(s,{x:50,y:50}).ports.length,1)});
test('versionamento incrementa versão',()=>{const s=createCustomSymbol({id:'custom-v',name:'V'});assert.equal(versionCustomSymbol(s).version,2)});
test('export/import H2F preserva custom symbol',()=>{const s=createCustomSymbol({id:'custom-io',name:'IO'});const back=importCustomLibrary(exportCustomLibrary([s]));assert.equal(back[0].id,'custom-io');assert.equal(back[0].custom,true)});
console.log(`Library Core: ${n}/${n} PASS`);
