import assert from 'node:assert/strict';
import {createOfflineState,setConnectivity,enqueueSync,nextSyncBatch,markSyncing,acknowledgeSync,markSyncError,markSyncConflict,resolveSyncConflict,createRecoveryCheckpoint,latestRecovery,syncSummary,mobileCapabilities,pointerGesturePolicy,offlineSecurityPolicy,SAVE_STATES} from '../src/editor-core/offline-sync.js';
let n=0; const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
let s=createOfflineState({deviceId:'T1',online:false});
t('offline inicial',()=>assert.equal(s.saveState,SAVE_STATES.OFFLINE));
s=enqueueSync(s,{entityId:'DOC-1',payload:{a:1},idempotencyKey:'K1'});t('fila offline',()=>assert.equal(syncSummary(s).pending,1));
let dup=enqueueSync(s,{entityId:'DOC-1',payload:{a:2},idempotencyKey:'K1'});t('idempotência',()=>assert.equal(dup.queue.length,1));
s=setConnectivity(s,true);t('reconexão',()=>assert.equal(s.online,true));
t('incremental ordenado',()=>assert.equal(nextSyncBatch(s,1)[0].idempotencyKey,'K1'));
s=markSyncing(s,[s.queue[0].id]);t('syncing',()=>assert.equal(s.queue[0].attempts,1));
s=acknowledgeSync(s,{id:s.queue[0].id,serverVersion:2});t('ack resumível',()=>assert.equal(syncSummary(s).synced,1));
s=enqueueSync(s,{entityId:'E2'});s=markSyncError(s,s.queue.at(-1).id,'net');t('erro visível',()=>assert.equal(s.saveState,SAVE_STATES.ERROR));
s=markSyncConflict(s,s.queue.at(-1).id,{serverVersion:3,remote:{x:2}});t('conflito explícito',()=>assert.equal(s.saveState,SAVE_STATES.CONFLICT));
s=resolveSyncConflict(s,s.queue.at(-1).id,{strategy:'MERGE',mergedPayload:{x:3}});t('merge retorna fila',()=>assert.equal(s.queue.at(-1).status,'PENDING'));
t('sem LWW implícito',()=>assert.throws(()=>resolveSyncConflict(s,s.queue.at(-1).id,{strategy:'LAST_WRITE_WINS'})));
s=createRecoveryCheckpoint(s,{documentId:'DOC-1',snapshot:{v:7},reason:'REFRESH'});t('recovery checkpoint',()=>assert.equal(latestRecovery(s,'DOC-1').snapshot.v,7));
t('mobile prioridades',()=>assert.ok(mobileCapabilities(390).includes('PHOTO')));t('tablet/desktop full editor',()=>assert.deepEqual(mobileCapabilities(900),['FULL_EDITOR']));
t('pointer events',()=>assert.equal(pointerGesturePolicy().engine,'Pointer Events'));t('gestos',()=>assert.ok(pointerGesturePolicy().gestures.includes('pinch')));t('stylus',()=>assert.equal(pointerGesturePolicy().stylus.supported,true));
t('IndexedDB criptografável',()=>assert.equal(offlineSecurityPolicy().storage,'IndexedDB'));t('Web Crypto',()=>assert.equal(offlineSecurityPolicy().encryption,'Web Crypto'));t('sem chave hardcoded',()=>assert.equal(offlineSecurityPolicy().hardcodedKeys,false));t('sem cache auth indiscriminado',()=>assert.equal(offlineSecurityPolicy().cacheAuthenticatedResponses,false));
console.log(`offline-sync ${n}/${n} PASS`);
