import assert from'node:assert/strict';
import{createPipeRun,isPipeRun,isLinearEntity,pipeRunGraphicLength,pipeSegmentGraphicLength,updatePipeEngineering,updatePipeSegment,movePipeWaypoint,addPipeWaypointProjected,removePipeWaypoint,movePipeRun,movePipeSegment,transformPipeRun,validatePipeRun,pipeRunSummary}from'../src/editor-core/piping.js';
import{moveSelection,resizeSelection,rotateSelection,selectionBounds}from'../src/editor-core/selection.js';
let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
const run=createPipeRun('PR-100',[{x:0,y:0},{x:100,y:0},{x:100,y:80}],{lineNumber:'4"-P-100-CC03',nominalSize:'4"',spec:'CC03',service:'Processo'});
t('create semantic run',()=>{assert.equal(run.kind,'pipe-run');assert.equal(run.segments.length,2);assert.equal(run.vertexIds.length,3);assert.equal(run.engineering.lineNumber,'4"-P-100-CC03')});
t('type guards',()=>{assert.ok(isPipeRun(run));assert.ok(isLinearEntity(run))});
t('stable initial ids',()=>{assert.deepEqual(run.vertexIds,['PR-100-V001','PR-100-V002','PR-100-V003']);assert.deepEqual(run.segments.map(s=>s.id),['PR-100-S001','PR-100-S002'])});
t('segment references',()=>{assert.equal(run.segments[0].startVertexId,'PR-100-V001');assert.equal(run.segments[0].endVertexId,'PR-100-V002')});
t('graphic length only',()=>{assert.equal(pipeRunGraphicLength(run),180);assert.equal(pipeSegmentGraphicLength(run,1),80);assert.equal(run.segments[0].physicalLength,null)});
t('engineering update',()=>{const q=updatePipeEngineering(run,{schedule:'40',material:'A106 Gr.B'});assert.equal(q.engineering.schedule,'40');assert.equal(q.engineering.material,'A106 Gr.B');assert.equal(q.points,run.points)});
t('segment metadata update',()=>{const q=updatePipeSegment(run,'PR-100-S001',{properties:{note:'trecho A'}});assert.equal(q.segments[0].properties.note,'trecho A')});
t('move waypoint preserves semantic ids',()=>{const q=movePipeWaypoint(run,1,{x:120,y:10});assert.deepEqual(q.vertexIds,run.vertexIds);assert.deepEqual(q.segments.map(s=>s.id),run.segments.map(s=>s.id));assert.deepEqual(q.points[1],{x:120,y:10})});
t('split creates stable new vertex/segment',()=>{const q=addPipeWaypointProjected(run,0,{x:40,y:20});assert.equal(q.points.length,4);assert.equal(q.vertexIds[1],'PR-100-V004');assert.equal(q.segments[0].id,'PR-100-S001');assert.equal(q.segments[1].id,'PR-100-S003');assert.ok(validatePipeRun(q).valid)});
t('split does not invent physical length',()=>{const withPhysical=updatePipeSegment(run,'PR-100-S001',{physicalLength:1250});const q=addPipeWaypointProjected(withPhysical,0,{x:50,y:0});assert.equal(q.segments[0].physicalLength,null);assert.equal(q.segments[1].physicalLength,null)});
t('remove interior merges without inferring physical length',()=>{const q=addPipeWaypointProjected(run,0,{x:50,y:0});const r=removePipeWaypoint(q,1);assert.equal(r.points.length,3);assert.equal(r.segments.length,2);assert.ok(validatePipeRun(r).valid);assert.equal(r.segments[0].physicalLength,null)});
t('move run',()=>{const q=movePipeRun(run,5,-3);assert.deepEqual(q.points[0],{x:5,y:-3});assert.ok(validatePipeRun(q).valid)});
t('move segment',()=>{const q=movePipeSegment(run,0,0,10);assert.deepEqual(q.points[0],{x:0,y:10});assert.deepEqual(q.points[1],{x:100,y:10});assert.ok(validatePipeRun(q).valid)});
t('transform keeps topology ids',()=>{const q=transformPipeRun(run,p=>({x:p.x*2,y:p.y*2}));assert.deepEqual(q.segments.map(s=>s.id),run.segments.map(s=>s.id));assert.ok(validatePipeRun(q).valid)});
t('validation detects broken refs',()=>{const bad={...run,segments:run.segments.map((s,i)=>i?{...s}:{...s,startVertexId:'BAD'})};const v=validatePipeRun(bad);assert.equal(v.valid,false);assert.ok(v.issues.some(x=>x.startsWith('segment-ref-')))});
t('selection move preserves topology',()=>{const q=moveSelection([run],[run.id],10,5)[0];assert.ok(validatePipeRun(q).valid);assert.deepEqual(q.segments.map(s=>s.id),run.segments.map(s=>s.id))});
t('selection resize preserves topology',()=>{const b=selectionBounds([run],[run.id]);const q=resizeSelection([run],[run.id],'e',{x:b.maxX+100,y:b.minY},b)[0];assert.ok(validatePipeRun(q).valid);assert.deepEqual(q.vertexIds,run.vertexIds)});
t('selection rotate preserves topology',()=>{const b=selectionBounds([run],[run.id]);const q=rotateSelection([run],[run.id],b,{x:b.maxX,y:(b.minY+b.maxY)/2},{x:(b.minX+b.maxX)/2,y:b.maxY})[0];assert.ok(validatePipeRun(q).valid);assert.deepEqual(q.segments.map(s=>s.id),run.segments.map(s=>s.id))});
t('summary',()=>{const q=pipeRunSummary(run);assert.equal(q.segments,2);assert.equal(q.nominalSize,'4"');assert.equal(q.graphicLength,180)});
console.log(`PIPING_CORE ${n}/19 PASS`);
