import assert from 'node:assert/strict';
import { PERFORMANCE_BUDGETS, createPerformanceSample, evaluatePerformance, createSpatialHash, redactLogPayload, validateUploadDescriptor, securityBaseline, createAuditEvent, createRecoverySnapshot, recoveryPrompt, safeUserError, validateCriticalSecurityConfig } from '../src/editor-core/quality-hardening.js';
const ok=(n,fn)=>{fn();console.log(`PASS ${n}`)};
ok('budgets mensuráveis',()=>assert.deepEqual(PERFORMANCE_BUDGETS.elementBenchmarks,[1000,5000,10000,20000]));
ok('métricas obrigatórias',()=>{const s=createPerformanceSample({elementCount:1000,fps:60,dragLatencyMs:10,selectionLatencyMs:20,zoomLatencyMs:20,loadMs:100,saveMs:100,memoryBytes:1,documentBytes:2});assert.equal(Object.keys(s).length,9)});
ok('budget pass',()=>assert.equal(evaluatePerformance(createPerformanceSample({fps:60,dragLatencyMs:10,selectionLatencyMs:10,zoomLatencyMs:10,loadMs:10,saveMs:10})).pass,true));
ok('budget fail',()=>assert.equal(evaluatePerformance(createPerformanceSample({fps:20,dragLatencyMs:100,selectionLatencyMs:100,zoomLatencyMs:100,loadMs:3000,saveMs:2000})).pass,false));
ok('spatial hash consulta viewport',()=>{const h=createSpatialHash(100);h.insert({id:'a',bounds:{x:0,y:0,width:10,height:10}});h.insert({id:'b',bounds:{x:500,y:500,width:10,height:10}});assert.deepEqual(h.query({x:0,y:0,width:50,height:50}).map(x=>x.id),['a'])});
ok('spatial hash clear',()=>{const h=createSpatialHash();h.insert({id:'a',bounds:{x:0,y:0,width:1,height:1}});h.clear();assert.equal(h.size(),0)});
ok('redação de senha/token/secret',()=>{const r=redactLogPayload({senha:'x',token:'y',nested:{secret:'z',ok:1}});assert.equal(r.senha,'[REDACTED]');assert.equal(r.nested.ok,1)});
ok('upload válido privado + antimalware',()=>{const r=validateUploadDescriptor({name:'a.pdf',extension:'.pdf',mime:'application/pdf',size:10,magicValid:true});assert.equal(r.valid,true);assert.equal(r.private,true);assert.equal(r.antimalwareRequired,true)});
ok('upload MIME inválido',()=>assert.equal(validateUploadDescriptor({name:'x.exe',extension:'.exe',mime:'application/x-msdownload',size:10,magicValid:true}).valid,false));
ok('upload magic bytes inválidos',()=>assert.equal(validateUploadDescriptor({name:'a.pdf',extension:'.pdf',mime:'application/pdf',size:10,magicValid:false}).valid,false));
ok('baseline segurança completo',()=>assert.equal(validateCriticalSecurityConfig(securityBaseline()).valid,true));
ok('baseline detecta ausência',()=>assert.ok(validateCriticalSecurityConfig({...securityBaseline(),mfa:false}).missing.includes('mfa')));
ok('auditoria ação relevante',()=>assert.equal(createAuditEvent({action:'EXPORT',actorId:'u1'}).action,'EXPORT'));
ok('auditoria redige segredo',()=>assert.equal(createAuditEvent({action:'UPLOAD',actorId:'u1',metadata:{token:'x'}}).metadata.token,'[REDACTED]'));
ok('auditoria exige ator',()=>assert.throws(()=>createAuditEvent({action:'LOGIN'})));
ok('snapshot recuperação clona documento',()=>{const d={a:1};const s=createRecoverySnapshot(d,'CRASH');d.a=2;assert.equal(s.document.a,1)});
ok('prompt recuperação',()=>assert.match(recoveryPrompt(createRecoverySnapshot({})),/versão não salva/));
ok('erro não expõe stack',()=>assert.equal(safeUserError(new Error('Falha')).technicalDetailsVisible,false));
console.log('QUALITY_HARDENING_TESTS 18/18');
