import assert from'node:assert/strict';import fs from'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8'),core=fs.readFileSync(new URL('../src/editor-core/documentation.js',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
let n=0;const t=(name,fn)=>{fn();n++;console.log('PASS',name)};
t('documentation core imported',()=>assert.ok(main.includes("from'./editor-core/documentation.js'")));
t('toolbar exposes Cota',()=>assert.ok(main.includes("'Cota'")));
t('toolbar exposes Elevação',()=>assert.ok(main.includes("'Elevação'")));
t('toolbar exposes Coordenada',()=>assert.ok(main.includes("'Coordenada'")));
t('toolbar exposes Fluxo',()=>assert.ok(main.includes("'Fluxo'")));
t('toolbar exposes Norte',()=>assert.ok(main.includes("'Norte'")));
t('dimension uses two-click workflow',()=>assert.ok(main.includes("dimensionDraft.anchor")));
t('dimension engineering value editor exists',()=>assert.ok(main.includes('Dimensão de engenharia')));
t('dimension physical vs visual warning exists',()=>assert.ok(main.includes('Geometria visual e dimensão real permanecem independentes')));
t('elevation insertion exists',()=>assert.ok(main.includes('insertElevationAt')));
t('industrial coordinate insertion exists',()=>assert.ok(main.includes('insertCoordinateAt')));
t('flow insertion uses nearest pipe segment',()=>assert.ok(main.includes('insertFlowAt')));
t('flow direction can be reversed',()=>assert.ok(main.includes('reverseFlowArrow')));
t('north insertion associates sheet',()=>assert.ok(main.includes("sheetId:'SHEET-1'")));
t('north rotation editor exists',()=>assert.ok(main.includes('Rotação (°)')));
t('industrial coordinates explicitly separate GPS',()=>assert.ok(main.includes('separado de GPS')));
t('dimension types include required set',()=>assert.ok(core.includes("'linear','aligned','horizontal','vertical','angular','between-points','offset','elevation'")));
t('associative resolver exists',()=>assert.ok(core.includes('resolveAnchor')));
t('flow resolver follows run geometry',()=>assert.ok(core.includes('resolveFlowArrow')));
t('phase12 styles exist',()=>assert.ok(css.includes('FASE 12')));
console.log(`SHELL_PHASE12 ${n}/20 PASS`);
