import assert from'node:assert/strict';import fs from'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../src/style.css',import.meta.url),'utf8');let n=0;const t=(name,cond)=>{assert.ok(cond,name);n++;console.log('PASS',name)};
t('Snap Core importado',main.includes("from'./editor-core/snap.js'"));
t('ConnectionPoints renderizados',main.includes('<ConnectionPoints entities={entities}'));
t('SnapOverlay renderizado',main.includes('<SnapOverlay result={snapPreview}'));
t('snap em desenho',main.includes('const raw=eventWorld(e),sr=snapped(raw,e),p=sr.point'));
t('snap em waypoint',main.includes("interaction.type==='waypoint'"));
t('conexão física por snap',main.includes("connectPorts(g,interaction.sourcePortId,target"));
t('conexão ao finalizar PipeRun',main.includes("connectPorts(next,a,b,{kind:'physical-snap'})"));
t('Alt bypass documentado',main.includes('Segure Alt para ignorar temporariamente o snap'));
t('toggle connection points',main.includes('Connection points'));
t('toggle geometry',main.includes('Endpoints, vértices, interseções e midpoints'));
t('toggle smart guides',main.includes('Guias inteligentes'));
t('tolerância configurável',main.includes('Tolerância (px)'));
t('status de conexão no footer',main.includes('graphInfo.connections'));
t('CSS connection point',css.includes('.connectionPoint'));
t('CSS smart guide',css.includes('.smartGuide'));
t('CSS snap marker',css.includes('.snapMarker'));
console.log(`SHELL_PHASE9_PASS ${n}/16`);
