import assert from'node:assert/strict';
import{createPipeRun}from'../src/editor-core/piping.js';
import{createPolyline}from'../src/editor-core/polyline.js';
import{createGridConfig}from'../src/editor-core/grid.js';
import{collectEntitySnapCandidates,resolveSnap,SNAP_TYPES,SNAP_PRIORITY,snapLabel}from'../src/editor-core/snap.js';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS',name)};
const pipe=createPipeRun('PR-A',[{x:0,y:0},{x:100,y:0},{x:100,y:100}],{nominalSize:'4"'});
const line=createPolyline('LN-B',[{x:50,y:-50},{x:50,y:50}]);
test('prioridade port > endpoint > vertex > intersection > midpoint > alignment > grid',()=>assert.ok(SNAP_PRIORITY.port>SNAP_PRIORITY.endpoint&&SNAP_PRIORITY.endpoint>SNAP_PRIORITY.vertex&&SNAP_PRIORITY.vertex>SNAP_PRIORITY.intersection&&SNAP_PRIORITY.intersection>SNAP_PRIORITY.midpoint&&SNAP_PRIORITY.midpoint>SNAP_PRIORITY.alignment&&SNAP_PRIORITY.alignment>SNAP_PRIORITY.grid));
test('coleta portas nos endpoints de PipeRun',()=>{const c=collectEntitySnapCandidates([pipe]);assert.equal(c.filter(x=>x.type===SNAP_TYPES.PORT).length,2)});
test('coleta vértice interno',()=>assert.ok(collectEntitySnapCandidates([pipe]).some(x=>x.type==='vertex'&&x.vertexIndex===1)));
test('coleta midpoints',()=>assert.equal(collectEntitySnapCandidates([pipe]).filter(x=>x.type==='midpoint').length,2));
test('detecta interseção entre entidades',()=>assert.ok(collectEntitySnapCandidates([pipe,line]).some(x=>x.type==='intersection'&&Math.abs(x.point.x-50)<1e-9&&Math.abs(x.point.y)<1e-9)));
test('snap em port tem prioridade sobre endpoint coincidente',()=>{const r=resolveSnap({x:2,y:1},{entities:[pipe],zoom:1,tolerancePx:10});assert.equal(r.candidate.type,'port');assert.deepEqual(r.point,{x:0,y:0})});
test('snap tolerância é screen-space',()=>{assert.equal(resolveSnap({x:8,y:0},{entities:[pipe],zoom:2,tolerancePx:10,types:['port']}).snapped,false);assert.equal(resolveSnap({x:4,y:0},{entities:[pipe],zoom:2,tolerancePx:10,types:['port']}).snapped,true)});
test('grid cartesiano',()=>{const r=resolveSnap({x:43,y:39},{entities:[],gridConfig:createGridConfig({mode:'cartesian',spacing:20}),zoom:1,tolerancePx:10});assert.deepEqual(r.point,{x:40,y:40});assert.equal(r.candidate.type,'grid')});
test('Alt/bypass desativa snap',()=>assert.equal(resolveSnap({x:2,y:1},{entities:[pipe],bypass:true}).snapped,false));
test('excludeEntityId evita auto-snap',()=>assert.equal(resolveSnap({x:1,y:1},{entities:[pipe],excludeEntityId:'PR-A'}).snapped,false));
test('filtro de tipos funciona',()=>{const r=resolveSnap({x:1,y:1},{entities:[pipe],types:['grid'],gridConfig:createGridConfig({mode:'cartesian',spacing:20})});assert.equal(r.candidate.type,'grid')});
test('smart guide X',()=>{const box={id:'B',x:200,y:200,width:100,height:100};const r=resolveSnap({x:202,y:350},{entities:[box],tolerancePx:5});assert.equal(r.candidate.type,'alignment');assert.equal(r.point.x,200);assert.ok(r.guides.length)});
test('label em português',()=>assert.equal(snapLabel({snapped:true,candidate:{type:'port'}}),'Porta'));
console.log(`SNAP_CORE_PASS ${n}/13`);
