import assert from 'node:assert/strict';
import {rankSymbolCandidates,decisionForConfidence,createSymbolDetection,confirmSymbolDetection,rejectSymbolDetection,detectionToNativeEntity,recognitionSummary,normalizeFeatureVector} from '../src/editor-core/symbol-recognition.js';
let n=0;const t=(name,fn)=>{fn();n++;console.log(`PASS symbol-recognition: ${name}`)};
t('normalize features',()=>assert.equal(normalizeFeatureVector({circularity:2}).circularity,1));
t('valve family ranks valve',()=>assert.equal(rankSymbolCandidates({familyHint:'valve',ports:2})[0].class,'VÁLVULAS'));
t('tee hint ranks tee',()=>assert.equal(rankSymbolCandidates({familyHint:'tee',primitiveHint:'tee',ports:3,branchCount:1})[0].symbolId,'tee'));
t('instrument circular evidence',()=>assert.equal(rankSymbolCandidates({familyHint:'instrument',circularity:.9})[0].class,'INSTRUMENTAÇÃO'));
t('alternatives bounded',()=>assert.equal(rankSymbolCandidates({familyHint:'valve'},{limit:3}).length,3));
t('auto threshold',()=>assert.equal(decisionForConfidence(.9),'AUTO_ACCEPT'));
t('review threshold',()=>assert.equal(decisionForConfidence(.7),'REVIEW'));
t('reject threshold',()=>assert.equal(decisionForConfidence(.2),'REJECT'));
t('detection bbox retained',()=>assert.deepEqual(createSymbolDetection({bbox:{x:1,y:2,width:3,height:4}}).bbox,{x:1,y:2,width:3,height:4}));
t('detection has alternatives',()=>assert.ok(createSymbolDetection({bbox:{x:0,y:0,width:10,height:10},features:{familyHint:'valve'}}).alternatives.length>1));
t('confirm explicit alternative',()=>assert.equal(confirmSymbolDetection(createSymbolDetection({id:'d1',bbox:{x:0,y:0,width:1,height:1}}),'tee').symbolId,'tee'));
t('reject records reason',()=>assert.equal(rejectSymbolDetection(createSymbolDetection({bbox:{x:0,y:0,width:1,height:1}}),'noise').rejectionReason,'noise'));
t('unconfirmed cannot become entity',()=>assert.throws(()=>detectionToNativeEntity(createSymbolDetection({bbox:{x:0,y:0,width:1,height:1}}),{x:0,y:0})));
t('confirmed becomes proposal entity',()=>{const d=confirmSymbolDetection(createSymbolDetection({id:'d2',bbox:{x:0,y:0,width:1,height:1},features:{familyHint:'tee',primitiveHint:'tee',ports:3,branchCount:1}}));assert.equal(detectionToNativeEntity(d,{x:2,y:3}).status,'CONFIRMED')});
t('summary counts decisions',()=>{const a=createSymbolDetection({bbox:{x:0,y:0,width:1,height:1}}),b=confirmSymbolDetection(a,'tee');assert.equal(recognitionSummary([a,b]).total,2)});
console.log(`Symbol Recognition Core: ${n}/15 PASS`);
