import assert from'node:assert/strict';import fs from'node:fs';
const src=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
const shell=fs.readFileSync(new URL('../src/ui/cad-shell.jsx',import.meta.url),'utf8');
let n=0;const test=(name,ok)=>{assert.ok(ok,name);n++;console.log('PASS',name)};
test('menu superior usa componente funcional',src.includes('<MenuBar menus={shellMenus}/>')&&shell.includes('role="menu"'));
for(const name of ['Arquivo','Editar','Exibir','Inserir','Organizar','Inspeção','Revisão','Ajuda'])test('menu '+name,src.includes(`label:'${name}'`));
test('toolbar usa ícones SVG locais',src.includes('<ToolButton')&&shell.includes('<svg className="cadIcon"'));
test('tooltips acessíveis hover/focus',shell.includes('data-tooltip={tip}')&&css.includes(':focus-visible::after'));
test('toolbar proíbe scroll horizontal',css.includes('.toolbar{')&&!css.match(/\.toolbar\{[^}]*overflow-x\s*:\s*(auto|scroll)/));
test('ações secundárias migram para Mais',src.includes('<ToolbarMore items={moreTools}/>')&&css.includes('.toolbarMorePopup'));
test('propriedades possuem ocultar e auto-hide',src.includes('autoHide={rightMode===')&&src.includes("setRightMode(m=>m==='auto'?'open':'auto')"));
test('estado dos painéis é persistido',src.includes("localStorage.setItem('h2f.ui.left'")&&src.includes("localStorage.setItem('h2f.ui.rightMode'"));
test('painéis estreitos viram overlay',css.includes('@media(max-width:1100px)')&&css.includes('position:absolute'));
test('paleta de comandos executa ação',src.includes('runCommand(cmd.id)'));
test('Exportar PDF existe no menu Arquivo',src.includes("{label:'Exportar',children:[")&&src.includes("{label:'PDF',action:exportPdf}"));
test('itens indisponíveis possuem motivo',src.includes("disabled:disabled('Editor de formato")&&shell.includes('title={disabled&&reason?reason:undefined}'));
test('breakpoints exigidos têm tratamento',css.includes('@media(max-width:1680px)')&&css.includes('@media(max-width:1366px)')&&css.includes('@media(max-width:1024px)'));
console.log(`UX-02 Shell: ${n}/${n} PASS`);
