import assert from'node:assert/strict';
import{BUILTIN_SYMBOLS,getSymbol,libraryStats,validateLibrary}from'../src/editor-core/library.js';
import{createPipeRun}from'../src/editor-core/piping.js';
import{createEngineeringGraph,registerPipeRun,graphStats,graphMountStats,validateEngineeringGraph,areNodesConnected,unregisterComponent}from'../src/editor-core/engineering-graph.js';
import{createInspectionStore,inspectionStats,validateInspectionStore,addWeld,createWeld}from'../src/editor-core/inspection.js';
import{insertUx06MarkerTransaction,registerUx06RecordTransaction,ux06NdtMethod,isUx06Symbol,validateUx06Markers,ux06MarkerStatus}from'../src/editor-core/ux06-markers.js';
let passed=0;const test=(n,f)=>{f();passed++;console.log('PASS',n)};
const run=createPipeRun('PR-601',[{x:0,y:0},{x:120,y:0}],{lineNumber:'6-P-601'});
const initial=()=>({entities:[run],graph:registerPipeRun(createEngineeringGraph(),run),inspectionStore:createInspectionStore()});
const place=(id,symbol,options={})=>insertUx06MarkerTransaction(initial(),{symbol:getSymbol(symbol),id,point:{x:40,y:0},...options});
const mount=(id,symbol)=>place(id,symbol,{runId:'PR-601',segmentIndex:0});
test('catalog has 227 symbols and 11 categories',()=>{const s=libraryStats();assert.equal(s.symbols,227);assert.deepEqual(['INSPEÇÃO','END','ANOTAÇÕES','SÍMBOLOS DE FOLHA'].map(c=>s.byCategory[c]),[19,23,16,16])});
test('UX-03 symbol schema is valid',()=>assert.equal(validateLibrary().valid,true));
test('UX-05 symbol families are preserved',()=>{for(const id of['valve-gate','support-trunnion','equip-pump-centrifugal','inst-pt'])assert.ok(getSymbol(id))});
test('all UX-06 glyph definitions lack physical ports',()=>{for(const s of BUILTIN_SYMBOLS.filter(isUx06Symbol)){assert.equal(s.portDefinitions.length,0,s.id);assert.equal(s.placement.inline,false,s.id)}});
test('all required NDT families have distinct metadata',()=>{for(const id of['ndt-ut','ndt-paut','ndt-tofd','ndt-rfa','ndt-iris','ndt-pec','ndt-pmi'])assert.equal(getSymbol(id).category,'END')});
test('PMI technique is preserved with OTHER, PAUT remains PAUT',()=>{assert.equal(ux06NdtMethod(getSymbol('ndt-pmi')),'OTHER');assert.equal(ux06NdtMethod(getSymbol('ndt-paut')),'PAUT')});
test('inspection support and annotation glyph metadata present',()=>{for(const id of['insp-tml','insp-cml','insp-weld-butt','insp-corrosion','ann-cloud','ann-warning','sheet-match-line','sheet-section'])assert.ok(getSymbol(id))});
test('physical TML marker is nonconductive and does not split PipeRun',()=>{const x=mount('I-1','insp-tml');assert.equal(x.ok,true);assert.equal(graphMountStats(x.graph).mounts,1);assert.equal(graphStats(x.graph).connections,0);assert.equal(areNodesConnected(x.graph,'I-1-NODE','PR-601-V001'),false);assert.equal(validateEngineeringGraph(x.graph).valid,true)});
test('placing marker never fabricates measurement or inspection',()=>{const x=mount('I-2','insp-tml');assert.equal(x.inspectionStore.points.length,0);assert.equal(x.inspectionStore.measurements.length,0);assert.match(ux06MarkerStatus(x.entities.at(-1)),/SOMENTE MARCADOR/)});
test('explicit TML registration creates record without measurement',()=>{const x=mount('T-1','insp-tml');const r=registerUx06RecordTransaction(x,{markerId:'T-1'});assert.equal(r.ok,true);assert.equal(inspectionStats(r.inspectionStore).tml,1);assert.equal(r.inspectionStore.measurements.length,0);assert.equal(r.entities.at(-1).ux06.recordState,'PLANNED');assert.equal(validateUx06Markers(r.entities,r.graph,r.inspectionStore).valid,true)});
test('CML is distinct from TML',()=>{const r=registerUx06RecordTransaction(mount('C-1','insp-cml'),{markerId:'C-1'});assert.equal(r.ok,true);assert.equal(r.inspectionStore.points[0].type,'CML')});
test('weld record starts planned',()=>{const r=registerUx06RecordTransaction(mount('W-1','insp-weld-butt'),{markerId:'W-1'});assert.equal(r.ok,true);assert.equal(r.inspectionStore.welds[0].status,'PLANNED')});
test('NDT record remains planned without automatic result or acceptance',()=>{const r=registerUx06RecordTransaction(mount('U-1','ndt-paut'),{markerId:'U-1'});assert.equal(r.ok,true);assert.equal(r.inspectionStore.ndt[0].method,'PAUT');assert.equal(r.inspectionStore.ndt[0].result,'');assert.equal(r.inspectionStore.ndt[0].acceptance,null);assert.equal(validateInspectionStore(r.inspectionStore).length,0)});
test('repeat registration is refused atomically',()=>{const x=registerUx06RecordTransaction(mount('U-2','ndt-paut'),{markerId:'U-2'});const y=registerUx06RecordTransaction(x,{markerId:'U-2'});assert.equal(y.ok,false);assert.equal(y.inspectionStore.ndt.length,1)});

test('visual damage marker never automatically creates anomaly',()=>{const x=mount('D-1','insp-corrosion');const y=registerUx06RecordTransaction(x,{markerId:'D-1'});assert.equal(y.ok,false);assert.equal(y.inspectionStore.points.length,0)});
test('free NDT marker cannot register without physical target',()=>{const x=place('E-1','ndt-ut',{point:{x:240,y:100}});assert.equal(registerUx06RecordTransaction(x,{markerId:'E-1'}).ok,false)});
test('free NDT can explicitly link to existing weld',()=>{const s=initial();s.inspectionStore=addWeld(s.inspectionStore,createWeld({id:'W-601',number:'W-601',target:{entityId:'PR-601'}}));const x=insertUx06MarkerTransaction(s,{symbol:getSymbol('ndt-rt'),id:'RT-601',point:{x:240,y:100}});const y=registerUx06RecordTransaction(x,{markerId:'RT-601',target:{kind:'weld',id:'W-601'}});assert.equal(y.ok,true);assert.equal(y.inspectionStore.welds[0].ndtIds.length,1)});
test('sheet symbols need explicit sheet identifier',()=>{assert.equal(place('S-1','sheet-match-line').ok,false);const x=place('S-2','sheet-match-line',{sheetId:'SHEET-1'});assert.equal(x.ok,true);assert.equal(x.entities.at(-1).ux06.sheetId,'SHEET-1')});
test('editorial annotation is not a process component',()=>{const x=place('ANN-1','ann-cloud',{point:{x:240,y:100}});assert.equal(x.ok,true);assert.equal(graphMountStats(x.graph).mounts,0);assert.equal(graphStats(x.graph).connections,0)});
test('registered marker must keep its record',()=>{const x=registerUx06RecordTransaction(mount('T-3','insp-tml'),{markerId:'T-3'});assert.equal(validateUx06Markers(x.entities,x.graph,initial().inspectionStore).valid,false)});
test('deleting physical marker removes graph mount',()=>{const x=mount('RM-1','insp-tml');const g=unregisterComponent(x.graph,'RM-1');assert.equal(graphMountStats(g).mounts,0);assert.equal(validateEngineeringGraph(g).valid,true)});
test('nonexistent PipeRun and duplicate IDs rollback',()=>{assert.equal(place('B-1','insp-tml',{runId:'MISSING',segmentIndex:0}).ok,false);const x=mount('B-2','insp-tml');const y=insertUx06MarkerTransaction(x,{symbol:getSymbol('insp-cml'),id:'B-2',point:{x:40,y:0}});assert.equal(y.ok,false);assert.equal(y.entities,x.entities)});
console.log('UX-06 Inspection END Annotations Sheet: '+passed+'/'+passed+' PASS');
