import assert from'node:assert/strict';
import{createCustomSymbol,createSymbolEntityFrom,BUILTIN_SYMBOLS,libraryStats,validateLibrary}from'../src/editor-core/library.js';
import{UX07_BOUNDS,UX07_MAX_PRIMITIVES,ux07DefaultPrimitive,ux07GesturePrimitive,ux07PrimitiveErrors,ux07ValidateShape,ux07SafeCreate,ux07UpdatePrimitive,ux07DeletePrimitive,ux07MovePrimitive,ux07TranslatePrimitive,ux07AddReferencePoint,ux07PrepareRevision,ux07MergeImported,ux07ParseLibrary,ux07SerializeLibrary,ux07RestoreSaved}from'../src/editor-core/ux07-custom-shapes.js';
let passed=0;const test=(name,run)=>{run();passed++;console.log('PASS',name)};
const shape=(id='custom-700')=>createCustomSymbol({id,name:'Teste '+id,scope:'PROJECT',primitives:[ux07DefaultPrimitive('circle')]});
test('UX06 builtin catalog unchanged at 227',()=>{assert.equal(libraryStats().symbols,227);assert.equal(validateLibrary().valid,true)});
test('UX07 viewport is 72x46',()=>assert.deepEqual(UX07_BOUNDS,{width:72,height:46}));
test('8 existing primitive contracts are supported',()=>{for(const t of['line','polyline','arc','circle','ellipse','rectangle','polygon','text'])assert.equal(ux07PrimitiveErrors(ux07DefaultPrimitive(t)).length,0,t)});
test('all drawing tools create valid geometry from pointer gesture',()=>{for(const t of['line','polyline','arc','circle','ellipse','rectangle','polygon','text'])assert.equal(ux07PrimitiveErrors(ux07GesturePrimitive(t,{x:10,y:8},{x:61,y:37})).length,0,t)});
test('gesture bounds clamp out-of-scene positions',()=>{const x=ux07GesturePrimitive('line',{x:-900,y:-10},{x:900,y:800});assert.deepEqual([x.x1,x.y1,x.x2,x.y2],[0,0,72,46])});
test('circles, ellipses and rectangles with invalid dimensions are refused',()=>{for(const p of[{type:'circle',cx:22,cy:20,r:-2},{type:'ellipse',cx:22,cy:20,rx:1,ry:0},{type:'rectangle',x:3,y:4,width:0,height:18}])assert.ok(ux07PrimitiveErrors(p).length)});
test('polyline requires at least two finite points',()=>assert.ok(ux07PrimitiveErrors({type:'polyline',points:[[0,0],[NaN,2]]}).length));
test('polygon requires at least 3 points',()=>assert.ok(ux07PrimitiveErrors({type:'polygon',points:[[0,0],[1,2]]}).length));
test('text cannot contain control chars after safe creation',()=>{const x=ux07SafeCreate({...shape(),primitives:[{type:'text',x:36,y:23,text:'HI\u0000END'}]});assert.equal(x.primitives[0].text,'HI END')});
test('text rejects excessive length',()=>assert.ok(ux07PrimitiveErrors({type:'text',x:2,y:3,text:'X'.repeat(100)}).length));
test('cannot save form without geometry',()=>assert.equal(ux07ValidateShape(createCustomSymbol({id:'custom-empty',name:'EMPTY'})).valid,false));
test('valid custom shape can be saved',()=>assert.equal(ux07ValidateShape(shape()).valid,true));
test('reject built-in ID shadowing',()=>assert.equal(ux07ValidateShape({...shape(),id:'valve-gate'}).valid,false));
test('reject unsafe custom connection role',()=>assert.equal(ux07ValidateShape({...shape(),connectionPoints:[{id:'A',x:0,y:23,role:'process'}]}).valid,false));
test('reference point addition uses unique IDs',()=>{let x=shape();x=ux07AddReferencePoint(x,{x:0,y:23});x=ux07AddReferencePoint(x,{x:72,y:23});assert.deepEqual(x.connectionPoints.map(p=>p.id),['REF1','REF2']);assert.equal(ux07ValidateShape(x).valid,true)});
test('reference point addition enforces max 16',()=>{let x=shape();for(let i=0;i<16;i++)x=ux07AddReferencePoint(x,{x:i,y:23});assert.throws(()=>ux07AddReferencePoint(x,{x:20,y:20}),/limit/)});
test('translation obeys 72x46 geometry bounds',()=>{const p=ux07TranslatePrimitive(ux07DefaultPrimitive('line'),999,999);assert.equal(p.x2,72);assert.equal(p.y2,46)});
test('translation shifts polyline vertices',()=>{const p=ux07TranslatePrimitive({type:'polyline',points:[[10,12],[20,25]]},4,5);assert.deepEqual(p.points,[[14,17],[24,30]])});
test('update selected primitive leaves original immutable',()=>{const a=shape(),b=ux07UpdatePrimitive(a,0,{cx:16});assert.equal(a.primitives[0].cx,36);assert.equal(b.primitives[0].cx,16)});
test('reorder and delete are deterministic',()=>{let a={...shape(),primitives:[ux07DefaultPrimitive('circle'),ux07DefaultPrimitive('line')]};a=ux07MovePrimitive(a,0,1);assert.equal(a.primitives[0].type,'line');assert.equal(ux07DeletePrimitive(a,0).primitives[0].type,'circle')});
test('revision bumps and leaves previous version',()=>{const a=shape(),b=ux07PrepareRevision(a,{...a,name:'Rev B'});assert.equal(a.version,1);assert.equal(b.version,2);assert.equal(a.name,'Teste custom-700')});
test('revision cannot silently change symbol ID',()=>assert.throws(()=>ux07PrepareRevision(shape('custom-701'),shape('custom-702')),/Cannot change/) );
test('old placed entities preserve snapshot after new revision',()=>{const a=shape(),placed={...createSymbolEntityFrom(a,{x:200,y:200}),symbolDefinition:structuredClone(a)};const revised=ux07PrepareRevision(a,{...a,primitives:[ux07DefaultPrimitive('rectangle')]});assert.equal(placed.symbolDefinition.primitives[0].type,'circle');assert.equal(revised.primitives[0].type,'rectangle')});
test('two same-ID equal-version different geometries conflict',()=>assert.throws(()=>ux07MergeImported([shape()],[{...shape(),primitives:[ux07DefaultPrimitive('ellipse')]}]),/Version conflict/));
test('higher revision updates imported symbol',()=>{const s=shape(),r=ux07PrepareRevision(s,{...s,name:'Nova'});assert.equal(ux07MergeImported([s],[r])[0].version,2)});
test('import roundtrip keeps custom geometry and reference points',()=>{let s=ux07AddReferencePoint(shape(),{x:0,y:23});const x=ux07ParseLibrary(ux07SerializeLibrary([s]));assert.deepEqual(x[0].primitives,s.primitives);assert.equal(x[0].connectionPoints[0].role,'reference')});
test('invalid and oversized imports are safely rejected',()=>{assert.throws(()=>ux07ParseLibrary('{"format":"bogus"}'));assert.throws(()=>ux07ParseLibrary('a'.repeat(1500001)),/large/)});
test('restore corrupt storage returns empty instead of crash',()=>assert.deepEqual(ux07RestoreSaved('{broken'),[]));
test('all new connection points are graphic-only and cannot fabricate process graph',()=>{const s=ux07AddReferencePoint(shape(),{x:0,y:23});const e=createSymbolEntityFrom(s,{x:200,y:100});assert.equal(e.ports.length,1);assert.equal(e.ports[0].role,'reference');assert.equal(e.placement.inline,false)});
test('max primitive limit refuses invalid project definitions',()=>{const a={...shape(),primitives:Array.from({length:UX07_MAX_PRIMITIVES+1},()=>ux07DefaultPrimitive('line'))};assert.equal(ux07ValidateShape(a).valid,false)});
test('new custom library export does not include built-in symbols',()=>{const result=JSON.parse(ux07SerializeLibrary([shape(),BUILTIN_SYMBOLS[0]]));assert.equal(result.symbols.length,1)});
console.log('UX-07 Custom Shape Creator: '+passed+'/'+passed+' PASS');
