import assert from'node:assert/strict';
import{createDocument,addSheet,duplicateSheet,createSheet,updateTitleBlock,sheetSize,revisionPayload}from'../src/editor-core/document-structure.js';
import{createInspectionStore,createMonitoringPoint,addMonitoringPoint,addMeasurement,createWeld,addWeld,createNDT,addNDT}from'../src/editor-core/inspection.js';
import{createPipeRun}from'../src/editor-core/piping.js';
import{BUILTIN_SYMBOLS}from'../src/editor-core/library.js';
import{UX08_SCHEMA,UX08_PAPER,UX08_TEMPLATE_STORAGE,UX08_PRESETS,ux08DefaultLayout,ux08Layout,ux08ValidateSheet,ux08SetPage,ux08UpdateLayout,ux08FrameGeometry,ux08NewTable,ux08AddTable,ux08EditTable,ux08RemoveTable,ux08TableData,ux08ApplyPreset,ux08SaveTemplate,ux08ReadTemplates,ux08SerializeTemplates}from'../src/editor-core/ux08-sheet-layout.js';
let n=0;const test=(name,f)=>{f();n++;console.log('PASS',name)};
const doc=()=>createDocument(),sheet=d=>d.sheets[0];
const inspected=()=>{let s=createInspectionStore();s=addWeld(s,createWeld({id:'W-1',number:'W01',status:'PLANNED',target:{entityId:'P-1'}}));s=addMonitoringPoint(s,createMonitoringPoint({id:'T-1',label:'T01',target:{entityId:'P-1'}}));s=addNDT(s,createNDT({id:'N-1',method:'PAUT',target:{kind:'weld',id:'W-1'},status:'PLANNED'}));return s};
const pipe=createPipeRun('P-1',[{x:0,y:0},{x:100,y:0}],{lineNumber:'6-UT-104',nominalSize:'6',material:'A106 Gr.B'});
const mat=()=>ux08NewTable('MATERIAL','TB-M');
test('legacy sheet receives nonmutating default UX08 layout',()=>{const d=doc(),x=ux08Layout(sheet(d));assert.equal(x.schema,UX08_SCHEMA);assert.equal(x.frame.visible,true);assert.equal(d.sheets[0].pageLayout,undefined)});
test('A0-A4 formats are accepted',()=>{for(const f of['A0','A1','A2','A3','A4'])assert.equal(ux08ValidateSheet({...createSheet(),format:f}).valid,true)});
test('portrait orientation changes physical page dimensions',()=>{const d=ux08SetPage(doc(),'SHEET-1',{format:'A4',orientation:'portrait'});assert.deepEqual(sheetSize(sheet(d)),{width:210,height:297})});
test('landscape orientation changes physical page dimensions',()=>{const d=ux08SetPage(doc(),'SHEET-1',{format:'A4',orientation:'landscape'});assert.deepEqual(sheetSize(sheet(d)),{width:297,height:210})});
test('custom sheet accepts dimensions in mm',()=>{const d=ux08SetPage(doc(),'SHEET-1',{format:'CUSTOM',customSize:[450,310]});assert.deepEqual(sheetSize(sheet(d)),{width:450,height:310})});
test('custom format rejects non-finite dimensions transactionally',()=>assert.throws(()=>ux08SetPage(doc(),'SHEET-1',{format:'CUSTOM',customSize:[NaN,420]}),/customSize/));
test('switching to A3 clears stale customSize',()=>{let d=ux08SetPage(doc(),'SHEET-1',{format:'CUSTOM',customSize:[460,300]});d=ux08SetPage(d,'SHEET-1',{format:'A3'});assert.equal(sheet(d).customSize,null);assert.deepEqual(sheetSize(sheet(d)),{width:420,height:297})});
test('margin changes are isolated from original document',()=>{const d=doc(),e=ux08UpdateLayout(d,'SHEET-1',{frame:{marginsMm:{left:15}}});assert.equal(ux08Layout(sheet(e)).frame.marginsMm.left,15);assert.equal(sheet(d).pageLayout,undefined)});
test('negative and oversized margins are refused',()=>{assert.throws(()=>ux08UpdateLayout(doc(),'SHEET-1',{frame:{marginsMm:{left:-2}}}),/margin-left/);assert.throws(()=>ux08UpdateLayout(doc(),'SHEET-1',{frame:{marginsMm:{top:50}}}),/margin-top/)});
test('zone count constrained to technical editing range',()=>{assert.throws(()=>ux08UpdateLayout(doc(),'SHEET-1',{frame:{zoneCount:22}}),/zone-count/)});
test('custom frame dimensions never move engineering entities',()=>{const d=doc(),copy=JSON.stringify(pipe),e=ux08UpdateLayout(d,'SHEET-1',{frame:{zones:false}});assert.equal(JSON.stringify(pipe),copy);assert.equal(e.revisions.length,0)});
test('frame geometry fits within fixed CAD paper viewport for all formats',()=>{for(const f of['A0','A1','A2','A3','A4'])for(const orientation of['portrait','landscape']){const g=ux08FrameGeometry({...createSheet(),format:f,orientation});assert.ok(g.paper.x>=0&&g.paper.y>=0&&g.paper.x+g.paper.width<=1120.001&&g.paper.y+g.paper.height<=720.001,f+orientation)}});
test('frame margins in mm scale with page fit transform',()=>{const d=doc(),g=ux08FrameGeometry(sheet(d));assert.ok(Math.abs(g.frame.x-g.paper.x-20*g.scale)<1e-7);assert.ok(Math.abs(g.frame.y-g.paper.y-10*g.scale)<1e-7)});
test('title block anchored bottom right of drawing frame',()=>{const g=ux08FrameGeometry(sheet(doc()));assert.ok(Math.abs(g.titleBlock.x+g.titleBlock.width-g.frame.x-g.frame.width)<1e-7);assert.ok(Math.abs(g.titleBlock.y+g.titleBlock.height-g.frame.y-g.frame.height)<1e-7)});
test('invalid oversized titleblock is refused',()=>assert.throws(()=>ux08UpdateLayout(doc(),'SHEET-1',{titleBlock:{widthMm:999}}),/titleBlock-size/));
test('all 7 table kinds have explicit headers',()=>{for(const kind of['MATERIAL','WELD','END','TML','REVISION','NOTES','MANUAL'])assert.ok(ux08TableData(ux08NewTable(kind,'K'),{sheet:sheet(doc()),document:doc()}).headers.length)});
test('material table groups quantity deterministically',()=>{const t=mat(),p={...pipe};const res=ux08TableData(t,{sheet:sheet(doc()),entities:[p,p]});assert.equal(res.total,1);assert.equal(res.rows[0][2],'2')});
test('tables do not silently invent approved NDT',()=>{const t=ux08NewTable('END','TEST');const r=ux08TableData(t,{sheet:sheet(doc()),inspection:inspected()});assert.equal(r.rows[0][2],'PLANNED');assert.equal(r.total,1)});
test('TML table reports SEM MEDIÇÃO until measured',()=>{const r=ux08TableData(ux08NewTable('TML','PT'),{sheet:sheet(doc()),inspection:inspected()});assert.equal(r.rows[0][2],'SEM MEDIÇÃO')});
test('TML table only uses real measurement records',()=>{let s=inspected();s=addMeasurement(s,{pointId:'T-1',thickness:6.35,date:'2026-10-08'});const r=ux08TableData(ux08NewTable('TML','PT'),{sheet:sheet(doc()),inspection:s});assert.equal(r.rows[0][2],'6.35 mm')});
test('revision table reads existing formal revisions only',()=>{const d={...doc(),revisions:[{revision:'B',state:'REVISADO',date:'2026-10-06T00:00:00Z'}]};const r=ux08TableData(ux08NewTable('REVISION','REV'),{sheet:sheet(d),document:d});assert.deepEqual(r.rows,[['B','REVISADO','2026-10-06']])});
test('table add/edit/delete transactions preserve original',()=>{let d=doc();const a=ux08AddTable(d,'SHEET-1',mat());assert.equal(ux08Layout(sheet(a)).tables.length,1);const b=ux08EditTable(a,'SHEET-1','TB-M',{anchor:'BOTTOM_LEFT'});assert.equal(ux08Layout(sheet(b)).tables[0].anchor,'BOTTOM_LEFT');const c=ux08RemoveTable(b,'SHEET-1','TB-M');assert.equal(ux08Layout(sheet(c)).tables.length,0);assert.equal(sheet(d).pageLayout,undefined)});
test('duplicate table identifier refused',()=>{const a=ux08AddTable(doc(),'SHEET-1',mat());assert.throws(()=>ux08AddTable(a,'SHEET-1',mat()),/duplicado/)});
test('table maxRows validated',()=>assert.throws(()=>ux08AddTable(doc(),'SHEET-1',ux08NewTable('END','N',{maxRows:100})),/table-rows/));
test('three professional H2F presets supported',()=>{assert.deepEqual(UX08_PRESETS.map(x=>x.id),['H2F_CORPORATIVO','H2F_CAMPO_END','H2F_MINIMALISTA']);for(const t of UX08_PRESETS){const d=ux08ApplyPreset(doc(),'SHEET-1',t.id);assert.equal(ux08Layout(sheet(d)).templateId,t.id)}});
test('applying field template keeps project and revision data',()=>{const d=updateTitleBlock(doc(),'SHEET-1',{project:'CLIENTE MACEIÓ',revision:'6'});const e=ux08ApplyPreset(d,'SHEET-1','H2F_CAMPO_END');assert.equal(sheet(e).titleBlock.project,'CLIENTE MACEIÓ');assert.equal(sheet(e).titleBlock.revision,'6')});
test('user template records typography and title block metadata',()=>{const d=updateTitleBlock(doc(),'SHEET-1',{project:'AL-01'});const t=ux08SaveTemplate(sheet(d),{id:'UX08_USER_001',name:'Template do Cliente'});assert.equal(t.dataFields.project,'AL-01')});
test('personal template export and import roundtrip safely',()=>{const t=ux08SaveTemplate(sheet(doc()),{id:'UX08_USER_002',name:'Cliente 2'}),back=ux08ReadTemplates(ux08SerializeTemplates([t]));assert.equal(back.length,1);assert.equal(back[0].id,t.id)});
test('invalid JSON templates rejected without eval',()=>assert.deepEqual(ux08ReadTemplates('{javascript injection'),[]));
test('built-in template ID collision rejected',()=>assert.throws(()=>ux08SaveTemplate(sheet(doc()),{id:'H2F_CORPORATIVO',name:'Falso'}),/reservado/));
test('template scope remains local and not automatically approved',()=>{const t=ux08SaveTemplate(sheet(doc()),{id:'UX08_USER_003',name:'Uso local'});assert.ok(UX08_TEMPLATE_STORAGE.includes('ux08'));assert.equal(t.dataFields.approvedBy||'', '')});
test('sheet duplicate retains layout fields (compatible with legacy document)',()=>{const a=ux08ApplyPreset(doc(),'SHEET-1','H2F_CAMPO_END'),b=duplicateSheet(a,'SHEET-1');assert.equal(b.sheets.length,2);assert.equal(ux08Layout(b.sheets[1]).style,'FIELD')});
test('baseline industrial catalog remains 227 symbols',()=>assert.equal(BUILTIN_SYMBOLS.length,227));
test('paper standard viewport retained for graph/editor regression',()=>assert.deepEqual(UX08_PAPER,{width:1120,height:720}));
test('revision payload includes sheet formatting without modifying revisions',()=>{const a=ux08ApplyPreset(doc(),'SHEET-1','H2F_CAMPO_END');assert.ok(revisionPayload(a,[pipe]).includes('H2F_CAMPO_END'));assert.equal(a.revisions.length,0)});
console.log('UX-08 Sheet Layout: '+n+'/'+n+' PASS');
