import assert from'node:assert/strict';import{createAnalysisJob,preprocessingPlan,otsuThreshold,binarize,detectAxisLines,detectDiagonalLines,detectLineCandidates,classifyOcrText,normalizeOcrToken,filterOcrTokens,aggregateConfidence,finalizeAnalysis,buildEvidence}from'../src/editor-core/vision-pipeline.js';
let pass=0;const t=(n,f)=>{f();pass++;console.log('PASS',n)};
t('job has mandatory stages',()=>assert.equal(createAnalysisJob('J').stages.length,10));
t('preprocess plans deskew and threshold',()=>{const p=preprocessingPlan({skewDeg:2,contrast:.5});assert.ok(p.some(x=>x.op==='deskew'));assert.equal(p.at(-1).op,'adaptive-threshold')});
t('otsu separates bimodal raster',()=>{const x=[...Array(20).fill(10),...Array(20).fill(230)];assert.ok(otsuThreshold(x)<230)});
t('binarize validates dimensions',()=>assert.throws(()=>binarize([1],2,2)));
t('binarize creates ink mask',()=>assert.deepEqual(binarize([0,255],2,1,127).data,[1,0]));
t('detect horizontal line',()=>{const d=Array(100).fill(0);for(let x=1;x<9;x++)d[5*10+x]=1;assert.ok(detectAxisLines({width:10,height:10,data:d},{minLength:6}).some(x=>x.orientation==='H'))});
t('detect vertical line',()=>{const d=Array(100).fill(0);for(let y=1;y<9;y++)d[y*10+5]=1;assert.ok(detectAxisLines({width:10,height:10,data:d},{minLength:6}).some(x=>x.orientation==='V'))});
t('detect diagonal line',()=>{const d=Array(100).fill(0);for(let i=1;i<9;i++)d[i*10+i]=1;assert.ok(detectDiagonalLines({width:10,height:10,data:d},{minLength:6}).some(x=>x.orientation==='D45'))});
t('combined candidates sorted confidence',()=>{const d=Array(100).fill(0);for(let x=1;x<9;x++)d[5*10+x]=1;const r=detectLineCandidates({width:10,height:10,data:d},{minLength:6});assert.ok(r.length);assert.ok(r.every((x,i)=>!i||r[i-1].confidence>=x.confidence))});
t('classifies dimension',()=>assert.equal(classifyOcrText('2850 mm'),'DIMENSION'));
t('classifies elevation',()=>assert.equal(classifyOcrText('EL. +12.500'),'ELEVATION'));
t('classifies line number',()=>assert.equal(classifyOcrText('4-P-04517'),'LINE_NUMBER'));
t('classifies tag',()=>assert.equal(classifyOcrText('XV-102'),'TAG'));
t('normalizes percent confidence',()=>assert.equal(normalizeOcrToken({text:'XV-102',confidence:87}).confidence,.87));
t('filters low confidence OCR',()=>assert.equal(filterOcrTokens([{text:'A',confidence:10},{text:'XV-102',confidence:90}],.5).length,1));
t('aggregates confidence',()=>assert.equal(aggregateConfidence([{confidence:.5},{confidence:1}]),.75));
t('finalize does not invent low confidence tokens',()=>{const j=finalizeAnalysis(createAnalysisJob('J'),{ocr:[{text:'?',confidence:5}]});assert.equal(j.detections.ocr.length,0)});
t('evidence summarizes classes',()=>{const j=finalizeAnalysis(createAnalysisJob('J',{sourceId:'U'}),{ocr:[{text:'XV-102',confidence:90}]});assert.equal(buildEvidence(j).classes.TAG,1)});
console.log(`Vision Pipeline: ${pass}/18 PASS`);
