const clone=p=>({x:Number(p.x),y:Number(p.y)});
export const ANNOTATION_KINDS=Object.freeze({TEXT:'text-note',TAG:'tag-label',LEADER:'leader'});
export function createTextNote(id,point,opts={}){return{id,kind:ANNOTATION_KINDS.TEXT,name:opts.name||'Texto',x:point.x,y:point.y,width:opts.width||180,height:opts.height||42,rotation:opts.rotation||0,text:opts.text||'Texto',fontSize:opts.fontSize||14,fontWeight:opts.fontWeight||400,align:opts.align||'left',multiline:opts.multiline!==false}}
export function createTagLabel(id,point,opts={}){return{id,kind:ANNOTATION_KINDS.TAG,name:opts.name||'TAG',x:point.x,y:point.y,width:opts.width||120,height:opts.height||30,rotation:opts.rotation||0,text:opts.text||'TAG',targetId:opts.targetId||null,prefix:opts.prefix||'',suffix:opts.suffix||''}}
export function createLeader(id,anchor,labelPoint,opts={}){return{id,kind:ANNOTATION_KINDS.LEADER,name:opts.name||'Leader',x:Math.min(anchor.x,labelPoint.x),y:Math.min(anchor.y,labelPoint.y),width:Math.max(1,Math.abs(labelPoint.x-anchor.x)),height:Math.max(1,Math.abs(labelPoint.y-anchor.y)),rotation:0,anchor:opts.anchorRef||{kind:'free',point:clone(anchor)},labelPoint:clone(labelPoint),elbow:opts.elbow?clone(opts.elbow):null,text:opts.text||'Anotação',arrow:opts.arrow!==false}}
export function formatTag(tag,entities=[]){if(tag.kind!==ANNOTATION_KINDS.TAG)return'';const target=entities.find(e=>e.id===tag.targetId);const value=target?.tag||target?.engineering?.lineNumber||target?.name||tag.text;return`${tag.prefix||''}${value||tag.text||''}${tag.suffix||''}`}
export function resolveAnnotationAnchor(anchor,entities=[]){if(!anchor)return null;if(anchor.kind==='free')return clone(anchor.point);const e=entities.find(x=>x.id===anchor.entityId);if(!e)return null;if(anchor.kind==='entity-center')return{x:e.x+e.width/2,y:e.y+e.height/2};if(anchor.kind==='vertex'&&e.points?.[anchor.index])return clone(e.points[anchor.index]);if(anchor.kind==='segment'&&e.points?.[anchor.index+1]){const a=e.points[anchor.index],b=e.points[anchor.index+1],t=anchor.t??.5;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}return null}
export function resolveLeader(leader,entities=[]){const anchor=resolveAnnotationAnchor(leader.anchor,entities);return{...leader,resolved:!!anchor,anchor:anchor||leader.anchor?.point||{x:leader.x,y:leader.y}}}
export function updateAnnotation(entity,patch={}){return{...entity,...patch}}
export function moveLeaderLabel(leader,point){return{...leader,labelPoint:clone(point),x:Math.min(resolveAnnotationAnchor(leader.anchor,[])?.x??leader.x,point.x),y:Math.min(resolveAnnotationAnchor(leader.anchor,[])?.y??leader.y,point.y)}}
export function annotationPlainText(entity,entities=[]){if(entity.kind===ANNOTATION_KINDS.TAG)return formatTag(entity,entities);return entity.text||''}
export function annotationBounds(entity,entities=[]){if(entity.kind!==ANNOTATION_KINDS.LEADER)return{minX:entity.x,minY:entity.y,maxX:entity.x+entity.width,maxY:entity.y+entity.height};const r=resolveLeader(entity,entities),pts=[r.anchor,r.labelPoint,r.elbow].filter(Boolean);return{minX:Math.min(...pts.map(p=>p.x)),minY:Math.min(...pts.map(p=>p.y)),maxX:Math.max(...pts.map(p=>p.x)),maxY:Math.max(...pts.map(p=>p.y))}}
