const nowIso=()=>new Date().toISOString();
export const DOUBT_STATUS=Object.freeze({PENDING:'PENDING',RESOLVED:'RESOLVED',IGNORED:'IGNORED'});
export const DOUBT_TYPES=Object.freeze(['SYMBOL','OCR','CROSSING','FLOW','DIRECTION','BRANCH','SYMBOL_POSITION','CONTINUITY','OTHER']);
export function createDoubtQueue(items=[]){return{version:1,items:items.map(normalizeDoubt),activeId:items[0]?.id||null};}
export function normalizeDoubt(d){if(!d?.id)throw new Error('doubt id required');return{id:d.id,type:DOUBT_TYPES.includes(d.type)?d.type:'OTHER',question:String(d.question||'Revisar reconhecimento'),status:Object.values(DOUBT_STATUS).includes(d.status)?d.status:DOUBT_STATUS.PENDING,confidence:Number.isFinite(Number(d.confidence))?Math.max(0,Math.min(1,Number(d.confidence))):null,hypothesis:d.hypothesis??null,alternatives:[...(d.alternatives||[])],crop:d.crop?{...d.crop}:null,sourceRef:d.sourceRef?{...d.sourceRef}:null,digitalRef:d.digitalRef?{...d.digitalRef}:null,answer:d.answer??null,resolution:null,createdAt:d.createdAt||nowIso(),updatedAt:d.updatedAt||d.createdAt||nowIso()};}
export function doubtFromSymbolDetection(d){if(!d?.id)throw new Error('detection required');return normalizeDoubt({id:`Q-${d.id}`,type:'SYMBOL',question:'Qual o símbolo industrial indicado?',confidence:d.confidence,hypothesis:d.symbolId,alternatives:d.alternatives.map(a=>({value:a.symbolId,label:a.name,confidence:a.confidence})),crop:d.bbox,sourceRef:{kind:'symbol-detection',id:d.id},digitalRef:{kind:'recognition-proposal',id:d.id}});}
export function doubtFromOcr(o){if(!o?.id)throw new Error('ocr id required');return normalizeDoubt({id:`Q-${o.id}`,type:'OCR',question:`Confirmar texto identificado: ${o.text||'?'}`,confidence:o.confidence,hypothesis:o.text||'',alternatives:(o.alternatives||[]).map(x=>typeof x==='string'?{value:x,label:x}:x),crop:o.bbox,sourceRef:{kind:'ocr',id:o.id}});}
export function createCrossingDoubt({id,bbox,confidence=null,lineIds=[]}){return normalizeDoubt({id,type:'CROSSING',question:'As linhas estão conectadas ou apenas se cruzam?',confidence,hypothesis:null,alternatives:[{value:'CONNECTED',label:'Conectadas'},{value:'CROSSING_ONLY',label:'Somente cruzamento'},{value:'UNKNOWN',label:'Não sei'}],crop:bbox,sourceRef:{kind:'crossing',lineIds}});}
export function enqueueDoubt(queue,doubt){const q={...queue,items:[...queue.items]};const n=normalizeDoubt(doubt);if(q.items.some(x=>x.id===n.id))return q;q.items.push(n);if(!q.activeId)q.activeId=n.id;return q;}
export function activeDoubt(queue){return queue.items.find(x=>x.id===queue.activeId)||null;}
export function selectDoubt(queue,id){if(!queue.items.some(x=>x.id===id))throw new Error('doubt not found');return{...queue,activeId:id};}
export function navigateDoubt(queue,direction=1,{pendingOnly=false}={}){const list=pendingOnly?queue.items.filter(x=>x.status===DOUBT_STATUS.PENDING):queue.items;if(!list.length)return{...queue,activeId:null};let i=list.findIndex(x=>x.id===queue.activeId);if(i<0)i=0;else i=(i+(direction>=0?1:-1)+list.length)%list.length;return{...queue,activeId:list[i].id};}
function update(queue,id,fn){let found=false;const items=queue.items.map(x=>{if(x.id!==id)return x;found=true;return fn(x)});if(!found)throw new Error('doubt not found');return{...queue,items};}
export function resolveDoubt(queue,id,answer,{userId='LOCAL_USER',note=''}={}){if(answer===undefined||answer===null||answer==='')throw new Error('answer required');return update(queue,id,d=>({...d,status:DOUBT_STATUS.RESOLVED,answer,resolution:{action:'CONFIRM_OR_EDIT',userId,note,resolvedAt:nowIso()},updatedAt:nowIso()}));}
export function markUnknown(queue,id,opts={}){return resolveDoubt(queue,id,'UNKNOWN',opts);}
export function ignoreDoubt(queue,id,{userId='LOCAL_USER',reason=''}={}){return update(queue,id,d=>({...d,status:DOUBT_STATUS.IGNORED,resolution:{action:'IGNORE',userId,reason,resolvedAt:nowIso()},updatedAt:nowIso()}));}
export function reopenDoubt(queue,id,{userId='LOCAL_USER'}={}){return update(queue,id,d=>({...d,status:DOUBT_STATUS.PENDING,answer:null,resolution:{action:'REOPEN',userId,reopenedAt:nowIso()},updatedAt:nowIso()}));}
export function doubtSummary(queue){const items=queue.items;return{total:items.length,resolved:items.filter(x=>x.status===DOUBT_STATUS.RESOLVED).length,pending:items.filter(x=>x.status===DOUBT_STATUS.PENDING).length,ignored:items.filter(x=>x.status===DOUBT_STATUS.IGNORED).length};}
export function focusTargets(doubt){return{original:doubt?.crop?{...doubt.crop}:null,digital:doubt?.digitalRef?{...doubt.digitalRef}:null};}
export function applyResolutionToRecognition(detection,doubt){if(!doubt||doubt.status!==DOUBT_STATUS.RESOLVED)throw new Error('resolved doubt required');if(doubt.answer==='UNKNOWN')return{...detection,confirmed:false,decision:'REVIEW',humanResolution:'UNKNOWN'};return{...detection,symbolId:String(doubt.answer),confirmed:true,decision:'AUTO_ACCEPT',confirmedBy:'HUMAN',humanResolution:String(doubt.answer)};}
export function canPromoteToEngineeringFact(doubt){return !!doubt&&doubt.status===DOUBT_STATUS.RESOLVED&&doubt.answer!=='UNKNOWN';}
