const clone=v=>structuredClone(v);
const uid=(p='ID')=>`${p}-${globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}`;
const assert=(x,m)=>{if(!x)throw new Error(m)};
export const CIRCUIT_TARGET_KINDS=Object.freeze(['line','pipe-segment','component','tml','cml']);
export const DAMAGE_STATES=Object.freeze(['CONSIDERAR','CONFIRMADO','EXCLUIDO']);
export const createIntegrityStore=()=>({circuits:[],damageCatalogs:[],assessments:[],events:[]});
const event=(type,entityId,actor='system',data={})=>Object.freeze({id:uid('IEVT'),type,entityId,actor,at:new Date().toISOString(),data:clone(data)});
export function createCorrosionCircuit({id=uid('CC'),name,code='',description='',targets=[],overlay={visible:true,label:'',opacity:.22},status='ACTIVE'}={}){
 assert(name,'circuit name required'); for(const t of targets){assert(CIRCUIT_TARGET_KINDS.includes(t.kind),'invalid circuit target');assert(t.id,'circuit target id required')}
 return {id,name,code,description,targets:clone(targets),overlay:{visible:overlay.visible!==false,label:overlay.label||name,opacity:Math.max(0,Math.min(1,Number(overlay.opacity??.22)))},status};
}
export function addCircuit(store,circuit,actor='system'){assert(!store.circuits.some(x=>x.id===circuit.id),'duplicate circuit');return {...clone(store),circuits:[...clone(store.circuits),clone(circuit)],events:[...clone(store.events),event('CIRCUIT_CREATED',circuit.id,actor)]}}
export function setCircuitTargets(store,id,targets,actor='system'){const s=clone(store),c=s.circuits.find(x=>x.id===id);assert(c,'circuit not found');for(const t of targets){assert(CIRCUIT_TARGET_KINDS.includes(t.kind),'invalid circuit target');assert(t.id,'circuit target id required')}c.targets=clone(targets);s.events.push(event('CIRCUIT_TARGETS_UPDATED',id,actor,{count:targets.length}));return s}
export function setCircuitOverlay(store,id,patch){const s=clone(store),c=s.circuits.find(x=>x.id===id);assert(c,'circuit not found');c.overlay={...c.overlay,...clone(patch)};if('opacity'in patch)c.overlay.opacity=Math.max(0,Math.min(1,Number(patch.opacity)));return s}
export function createDamageCatalog({id=uid('DMCAT'),version='1.0',name='Catálogo H2F',mechanisms=[],publishedAt=new Date().toISOString()}={}){assert(version,'catalog version required');const seen=new Set();for(const m of mechanisms){assert(m.code&&m.name,'mechanism code/name required');assert(!seen.has(m.code),'duplicate mechanism code');seen.add(m.code)}return {id,version,name,publishedAt,mechanisms:clone(mechanisms),immutable:true}}
export function addDamageCatalog(store,catalog,actor='system'){assert(!store.damageCatalogs.some(x=>x.id===catalog.id),'duplicate catalog');return {...clone(store),damageCatalogs:[...clone(store.damageCatalogs),clone(catalog)],events:[...clone(store.events),event('DAMAGE_CATALOG_ADDED',catalog.id,actor,{version:catalog.version})]}}
export function createDamageAssessment({id=uid('DMA'),catalogId,mechanismCode,target,state='CONSIDERAR',justification='',decidedBy='',decidedAt=null}={}){assert(catalogId&&mechanismCode,'catalog/mechanism required');assert(target?.kind&&target?.id,'damage target required');assert(DAMAGE_STATES.includes(state),'invalid damage state');if(state!=='CONSIDERAR')assert(justification.trim()&&decidedBy,'technical justification and human decision required');return {id,catalogId,mechanismCode,target:clone(target),state,justification,decidedBy,decidedAt:decidedAt||(state==='CONSIDERAR'?null:new Date().toISOString())}}
export function addDamageAssessment(store,a,actor='system'){const cat=store.damageCatalogs.find(x=>x.id===a.catalogId);assert(cat,'damage catalog not found');assert(cat.mechanisms.some(m=>m.code===a.mechanismCode),'mechanism not in catalog');return {...clone(store),assessments:[...clone(store.assessments),clone(a)],events:[...clone(store.events),event('DAMAGE_ASSESSMENT_CREATED',a.id,actor,{state:a.state})]}}
export function decideDamageAssessment(store,id,state,{actor,justification}={}){assert(['CONFIRMADO','EXCLUIDO'].includes(state),'human decision must confirm or exclude');assert(actor&&String(justification||'').trim(),'actor and justification required');const s=clone(store),a=s.assessments.find(x=>x.id===id);assert(a,'assessment not found');a.state=state;a.justification=justification;a.decidedBy=actor;a.decidedAt=new Date().toISOString();s.events.push(event(`DAMAGE_${state}`,id,actor,{justification}));return s}
export function integrityStats(store){return {circuits:store.circuits.length,activeCircuits:store.circuits.filter(x=>x.status==='ACTIVE').length,catalogVersions:store.damageCatalogs.length,consider:store.assessments.filter(x=>x.state==='CONSIDERAR').length,confirmed:store.assessments.filter(x=>x.state==='CONFIRMADO').length,excluded:store.assessments.filter(x=>x.state==='EXCLUIDO').length}}
export function validateIntegrityStore(store){const issues=[];for(const a of store.assessments){const cat=store.damageCatalogs.find(x=>x.id===a.catalogId);if(!cat)issues.push({code:'ORPHAN_DAMAGE_CATALOG',id:a.id});else if(!cat.mechanisms.some(m=>m.code===a.mechanismCode))issues.push({code:'UNKNOWN_DAMAGE_MECHANISM',id:a.id});if(a.state!=='CONSIDERAR'&&(!a.justification||!a.decidedBy))issues.push({code:'MISSING_HUMAN_JUSTIFICATION',id:a.id})}return issues}
