export const SAVE_STATES=Object.freeze({SAVING:'Salvando...',SAVED:'Salvo',OFFLINE:'Offline',ERROR:'Erro de salvamento',CONFLICT:'Conflito'});
export const SYNC_STATES=Object.freeze({PENDING:'PENDING',SYNCING:'SYNCING',SYNCED:'SYNCED',CONFLICT:'CONFLICT',ERROR:'ERROR'});
const clone=x=>structuredClone(x);
const uid=(p='op')=>`${p}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;
export function createOfflineState({deviceId='local-device',online=true}={}){return {deviceId,online,saveState:online?SAVE_STATES.SAVED:SAVE_STATES.OFFLINE,queue:[],checkpoints:[],lastSyncAt:null,sequence:0};}
export function setConnectivity(state,online){const s=clone(state);s.online=!!online;s.saveState=s.online?(s.queue.some(x=>x.status===SYNC_STATES.CONFLICT)?SAVE_STATES.CONFLICT:SAVE_STATES.SAVED):SAVE_STATES.OFFLINE;return s;}
export function enqueueSync(state,{entityId,entityType='document',operation='UPSERT',payload={},baseVersion=null,idempotencyKey=null}={}){if(!entityId)throw new Error('entityId obrigatório');const s=clone(state);const key=idempotencyKey||uid('idem');if(s.queue.some(x=>x.idempotencyKey===key))return s;s.sequence++;s.queue.push({id:uid('sync'),idempotencyKey:key,sequence:s.sequence,entityId,entityType,operation,payload:clone(payload),baseVersion,status:SYNC_STATES.PENDING,attempts:0,createdAt:new Date().toISOString(),error:null});s.saveState=s.online?SAVE_STATES.SAVING:SAVE_STATES.OFFLINE;return s;}
export function nextSyncBatch(state,limit=25){return state.queue.filter(x=>[SYNC_STATES.PENDING,SYNC_STATES.ERROR].includes(x.status)).sort((a,b)=>a.sequence-b.sequence).slice(0,limit).map(clone);}
export function markSyncing(state,ids){const set=new Set(ids);const s=clone(state);s.queue=s.queue.map(x=>set.has(x.id)?{...x,status:SYNC_STATES.SYNCING,attempts:x.attempts+1}:x);if(s.online)s.saveState=SAVE_STATES.SAVING;return s;}
export function acknowledgeSync(state,{id,idempotencyKey,serverVersion}={}){const s=clone(state);s.queue=s.queue.map(x=>(x.id===id||x.idempotencyKey===idempotencyKey)?{...x,status:SYNC_STATES.SYNCED,serverVersion,error:null}:x);s.lastSyncAt=new Date().toISOString();s.saveState=s.queue.some(x=>x.status===SYNC_STATES.CONFLICT)?SAVE_STATES.CONFLICT:(s.online?SAVE_STATES.SAVED:SAVE_STATES.OFFLINE);return s;}
export function markSyncError(state,id,error='Falha de sincronização'){const s=clone(state);s.queue=s.queue.map(x=>x.id===id?{...x,status:SYNC_STATES.ERROR,error}:x);s.saveState=s.online?SAVE_STATES.ERROR:SAVE_STATES.OFFLINE;return s;}
export function markSyncConflict(state,id,{serverVersion=null,remote=null}={}){const s=clone(state);s.queue=s.queue.map(x=>x.id===id?{...x,status:SYNC_STATES.CONFLICT,serverVersion,remote:clone(remote)}:x);s.saveState=SAVE_STATES.CONFLICT;return s;}
export function resolveSyncConflict(state,id,resolution){if(!['KEEP_LOCAL','KEEP_REMOTE','MERGE'].includes(resolution?.strategy))throw new Error('Estratégia explícita obrigatória');const s=clone(state);s.queue=s.queue.map(x=>x.id===id?{...x,status:resolution.strategy==='KEEP_REMOTE'?SYNC_STATES.SYNCED:SYNC_STATES.PENDING,resolution:clone(resolution),payload:resolution.strategy==='MERGE'?clone(resolution.mergedPayload):x.payload,error:null}:x);s.saveState=s.online?SAVE_STATES.SAVING:SAVE_STATES.OFFLINE;return s;}
export function createRecoveryCheckpoint(state,{documentId,snapshot,reason='AUTOSAVE'}={}){if(!documentId)throw new Error('documentId obrigatório');const s=clone(state);s.checkpoints.push({id:uid('recovery'),documentId,snapshot:clone(snapshot),reason,createdAt:new Date().toISOString(),sequence:s.sequence});if(s.checkpoints.length>20)s.checkpoints=s.checkpoints.slice(-20);return s;}
export function latestRecovery(state,documentId){return clone([...state.checkpoints].reverse().find(x=>x.documentId===documentId)||null);}
export function syncSummary(state){return {online:state.online,saveState:state.saveState,pending:state.queue.filter(x=>[SYNC_STATES.PENDING,SYNC_STATES.ERROR,SYNC_STATES.SYNCING].includes(x.status)).length,conflicts:state.queue.filter(x=>x.status===SYNC_STATES.CONFLICT).length,synced:state.queue.filter(x=>x.status===SYNC_STATES.SYNCED).length,lastSyncAt:state.lastSyncAt};}
export function mobileCapabilities(width){return width<600?['VIEW','SEARCH','NAVIGATE','EVIDENCE','PHOTO','TML','FIELD_DATA','ANSWER_AI']:['FULL_EDITOR'];}
export function pointerGesturePolicy(){return {engine:'Pointer Events',gestures:['pinch','pan','tap','long-press','drag'],stylus:{supported:true,precision:true,selection:true,annotation:true}};}
export function offlineSecurityPolicy(){return {storage:'IndexedDB',encryption:'Web Crypto',hardcodedKeys:false,cacheAuthenticatedResponses:false};}
