const clone=v=>structuredClone(v);
export const createHistory=(state,limit=100)=>({past:[],present:clone(state),future:[],limit});
export function commitHistory(h,next,label='edit'){return{...h,past:[...h.past,{state:clone(h.present),label}].slice(-h.limit),present:clone(next),future:[]}}
export function undoHistory(h){if(!h.past.length)return h;const x=h.past.at(-1);return{...h,past:h.past.slice(0,-1),present:clone(x.state),future:[{state:clone(h.present),label:x.label},...h.future]}}
export function redoHistory(h){if(!h.future.length)return h;const x=h.future[0];return{...h,past:[...h.past,{state:clone(h.present),label:x.label}].slice(-h.limit),present:clone(x.state),future:h.future.slice(1)}}
export function copyEntities(entities,ids){const set=new Set(ids),items=entities.filter(e=>set.has(e.id));return{mime:'application/x-h2f-entities',version:1,items:clone(items),sourceIds:[...ids]}}
export function cutEntities(entities,ids){const clip=copyEntities(entities,ids),set=new Set(ids);return{clipboard:clip,entities:entities.filter(e=>!set.has(e.id))}}
export function pasteEntities(entities,clip,{dx=20,dy=20,idFactory=(old,i)=>`${old}-COPY-${i+1}`}={}){if(!clip?.items)return{entities,createdIds:[]};const idMap=new Map(clip.items.map((e,i)=>[e.id,idFactory(e.id,i)]));const remap=v=>typeof v==='string'&&idMap.has(v)?idMap.get(v):v;const created=clip.items.map(e=>{const n=clone(e);n.id=idMap.get(e.id);if(Array.isArray(n.points))n.points=n.points.map(p=>({...p,x:p.x+dx,y:p.y+dy}));else{if(Number.isFinite(n.x))n.x+=dx;if(Number.isFinite(n.y))n.y+=dy}for(const k of ['targetId','entityId','parentId','groupId'])if(k in n)n[k]=remap(n[k]);return n});return{entities:[...entities,...created],createdIds:created.map(x=>x.id),idMap}}
export const duplicateEntities=(entities,ids,opts={})=>pasteEntities(entities,copyEntities(entities,ids),opts);
const bounds=e=>Array.isArray(e.points)?{minX:Math.min(...e.points.map(p=>p.x)),maxX:Math.max(...e.points.map(p=>p.x)),minY:Math.min(...e.points.map(p=>p.y)),maxY:Math.max(...e.points.map(p=>p.y))}:{minX:e.x,maxX:e.x+(e.width||0),minY:e.y,maxY:e.y+(e.height||0)};
const move=(e,dx,dy)=>Array.isArray(e.points)?{...e,points:e.points.map(p=>({...p,x:p.x+dx,y:p.y+dy}))}:{...e,x:(e.x||0)+dx,y:(e.y||0)+dy};
export function alignEntities(entities,ids,mode='left'){const chosen=entities.filter(e=>ids.includes(e.id));if(chosen.length<2)return entities;const bs=chosen.map(bounds),target=mode==='left'?Math.min(...bs.map(b=>b.minX)):mode==='right'?Math.max(...bs.map(b=>b.maxX)):mode==='top'?Math.min(...bs.map(b=>b.minY)):mode==='bottom'?Math.max(...bs.map(b=>b.maxY)):mode==='centerX'?(Math.min(...bs.map(b=>b.minX))+Math.max(...bs.map(b=>b.maxX)))/2:(Math.min(...bs.map(b=>b.minY))+Math.max(...bs.map(b=>b.maxY)))/2;return entities.map(e=>{if(!ids.includes(e.id))return e;const b=bounds(e);const dx=mode==='left'?target-b.minX:mode==='right'?target-b.maxX:mode==='centerX'?target-(b.minX+b.maxX)/2:0,dy=mode==='top'?target-b.minY:mode==='bottom'?target-b.maxY:mode==='centerY'?target-(b.minY+b.maxY)/2:0;return move(e,dx,dy)})}
export function distributeEntities(entities,ids,axis='x'){const chosen=entities.filter(e=>ids.includes(e.id));if(chosen.length<3)return entities;const sorted=[...chosen].sort((a,b)=>{const A=bounds(a),B=bounds(b);return axis==='x'?A.minX-B.minX:A.minY-B.minY});const first=bounds(sorted[0]),last=bounds(sorted.at(-1)),start=axis==='x'?first.minX:first.minY,end=axis==='x'?last.minX:last.minY,step=(end-start)/(sorted.length-1),targets=new Map(sorted.map((e,i)=>[e.id,start+i*step]));return entities.map(e=>{if(!targets.has(e.id))return e;const b=bounds(e),d=targets.get(e.id)-(axis==='x'?b.minX:b.minY);return move(e,axis==='x'?d:0,axis==='y'?d:0)})}
export function groupEntities(entities,ids,groupId){const set=new Set(ids);return entities.map(e=>set.has(e.id)?{...e,groupId}:e)}
export function ungroupEntities(entities,ids){const groups=new Set(entities.filter(e=>ids.includes(e.id)).map(e=>e.groupId).filter(Boolean));return entities.map(e=>groups.has(e.groupId)?(({groupId,...rest})=>rest)(e):e)}
export function reorderEntities(entities,ids,action){const set=new Set(ids),sel=entities.filter(e=>set.has(e.id)),rest=entities.filter(e=>!set.has(e.id));if(action==='front')return[...rest,...sel];if(action==='back')return[...sel,...rest];const a=[...entities];if(action==='forward')for(let i=a.length-2;i>=0;i--)if(set.has(a[i].id)&&!set.has(a[i+1].id))[a[i],a[i+1]]=[a[i+1],a[i]];if(action==='backward')for(let i=1;i<a.length;i++)if(set.has(a[i].id)&&!set.has(a[i-1].id))[a[i],a[i-1]]=[a[i-1],a[i]];return a}
export const lockEntities=(entities,ids,locked=true)=>entities.map(e=>ids.includes(e.id)?{...e,locked}:e);
export function mirrorEntities(entities,ids,axis='x'){const chosen=entities.filter(e=>ids.includes(e.id));if(!chosen.length)return entities;const bs=chosen.map(bounds),cx=(Math.min(...bs.map(b=>b.minX))+Math.max(...bs.map(b=>b.maxX)))/2,cy=(Math.min(...bs.map(b=>b.minY))+Math.max(...bs.map(b=>b.maxY)))/2;return entities.map(e=>{if(!ids.includes(e.id))return e;const tx=p=>({x:axis==='x'?2*cx-p.x:p.x,y:axis==='y'?2*cy-p.y:p.y});if(Array.isArray(e.points))return{...e,points:e.points.map(tx)};return axis==='x'?{...e,x:2*cx-(e.x+(e.width||0)),rotation:-(e.rotation||0)}:{...e,y:2*cy-(e.y+(e.height||0)),rotation:-(e.rotation||0)}})}
export function searchNavigator(entities,q=''){const s=q.trim().toLowerCase();if(!s)return entities;return entities.filter(e=>[e.id,e.name,e.tag,e.lineNumber,e.kind,e.text].some(v=>String(v||'').toLowerCase().includes(s)))}
export const COMMANDS=Object.freeze([{id:'undo',label:'Desfazer',shortcut:'Ctrl+Z'},{id:'redo',label:'Refazer',shortcut:'Ctrl+Y'},{id:'copy',label:'Copiar',shortcut:'Ctrl+C'},{id:'paste',label:'Colar',shortcut:'Ctrl+V'},{id:'duplicate',label:'Duplicar',shortcut:'Ctrl+D'},{id:'group',label:'Agrupar',shortcut:'Ctrl+G'},{id:'ungroup',label:'Desagrupar',shortcut:'Ctrl+Shift+G'},{id:'select-all',label:'Selecionar tudo',shortcut:'Ctrl+A'},{id:'delete',label:'Excluir',shortcut:'Delete'},{id:'fit',label:'Ajustar folha',shortcut:'F'}]);
export const searchCommands=(q='')=>COMMANDS.filter(c=>`${c.label} ${c.id} ${c.shortcut}`.toLowerCase().includes(q.toLowerCase()));
export function minimapViewport(worldBounds,viewport,size){const sx=size.width/(worldBounds.maxX-worldBounds.minX),sy=size.height/(worldBounds.maxY-worldBounds.minY),z=viewport.zoom;return{x:(-viewport.panX/z-worldBounds.minX)*sx,y:(-viewport.panY/z-worldBounds.minY)*sy,width:size.width/z,height:size.height/z}}
