import{createPipeRun}from'./piping.js';
import{createEngineeringGraph,syncPipeRun}from'./engineering-graph.js';
import{createSymbolEntityFrom,getSymbol}from'./library.js';
import{canPromoteToEngineeringFact}from'./human-in-loop.js';
const copy=o=>typeof structuredClone==='function'?structuredClone(o):JSON.parse(JSON.stringify(o));
const clamp=v=>Math.max(0,Math.min(1,Number(v)||0));
export const RECON_STATUS=Object.freeze({PROPOSED:'PROPOSED',CONFIRMED:'CONFIRMED',REJECTED:'REJECTED'});
export function createReconstructionSession({id='RECON-1',sourceRef=null}={}){return{id,version:1,sourceRef,proposals:[],entities:[],graph:createEngineeringGraph(),audit:[],createdAt:new Date().toISOString()}}
export function lineProposal({id,points,confidence=.5,sourceEvidenceIds=[],engineering={}}){if(!id||!Array.isArray(points)||points.length<2)throw new Error('line proposal requires id and >=2 points');return{id,kind:'PIPE_RUN',status:'PROPOSED',confidence:clamp(confidence),geometry:{points:points.map(p=>({x:Number(p.x),y:Number(p.y)}))},engineering:{...engineering},sourceEvidenceIds:[...sourceEvidenceIds],humanDoubtId:null}}
export function symbolProposal({id,symbolId,point,bbox=null,confidence=.5,sourceDetectionId=null}={}){if(!id||!symbolId||!point)throw new Error('symbol proposal fields required');return{id,kind:'SYMBOL',status:'PROPOSED',confidence:clamp(confidence),symbolId,point:{x:Number(point.x),y:Number(point.y)},bbox:bbox?{...bbox}:null,sourceEvidenceIds:sourceDetectionId?[sourceDetectionId]:[],humanDoubtId:null}}
export function addProposal(session,p){if(session.proposals.some(x=>x.id===p.id))throw new Error('duplicate proposal');return{...session,proposals:[...session.proposals,copy(p)]}}
export function bindHumanDoubt(session,proposalId,doubtId){return{...session,proposals:session.proposals.map(p=>p.id===proposalId?{...p,humanDoubtId:doubtId}:p)}}
export function proposalCanAutoConfirm(p,{threshold=.9}={}){return p.confidence>=threshold&&!p.humanDoubtId}
export function confirmProposal(session,proposalId,{doubt=null,userId='POLICY',threshold=.9,symbols}={}){const p=session.proposals.find(x=>x.id===proposalId);if(!p)throw new Error('proposal not found');const humanOk=doubt&&doubt.id===p.humanDoubtId&&canPromoteToEngineeringFact(doubt);if(!humanOk&&!proposalCanAutoConfirm(p,{threshold}))throw new Error('proposal requires human confirmation');let entities=[...session.entities],graph=session.graph,nativeId=`NATIVE-${p.id}`;
 if(p.kind==='PIPE_RUN'){const run=createPipeRun(nativeId,p.geometry.points,{...p.engineering,name:p.engineering.lineNumber||nativeId});entities.push({...run,reconstruction:{proposalId:p.id,confidence:p.confidence,sourceEvidenceIds:p.sourceEvidenceIds,confirmedBy:humanOk?'HUMAN':'POLICY'}});graph=syncPipeRun(graph,entities.at(-1));}
 else if(p.kind==='SYMBOL'){const symbol=(symbols||[]).find?.(x=>x.id===p.symbolId)||getSymbol(p.symbolId);if(!symbol)throw new Error('symbol not found');const e=createSymbolEntityFrom(symbol,p.point,{id:nativeId,tag:''});entities.push({...e,reconstruction:{proposalId:p.id,confidence:p.confidence,sourceEvidenceIds:p.sourceEvidenceIds,confirmedBy:humanOk?'HUMAN':'POLICY'}})}else throw new Error('unsupported proposal');
 const proposals=session.proposals.map(x=>x.id===p.id?{...x,status:'CONFIRMED',nativeEntityId:nativeId}:x);return{...session,entities,graph,proposals,audit:[...session.audit,{action:'CONFIRM',proposalId:p.id,nativeEntityId:nativeId,userId,mode:humanOk?'HUMAN':'POLICY'}]}}
export function rejectProposal(session,proposalId,{userId='LOCAL_USER',reason=''}={}){if(!session.proposals.some(x=>x.id===proposalId))throw new Error('proposal not found');return{...session,proposals:session.proposals.map(p=>p.id===proposalId?{...p,status:'REJECTED',rejectionReason:reason}:p),audit:[...session.audit,{action:'REJECT',proposalId,userId,reason}]}}
export function reconstructFromEvidence({lineCandidates=[],symbolDetections=[],sourceRef=null,threshold=.9}={}){let s=createReconstructionSession({sourceRef});for(const l of lineCandidates)s=addProposal(s,lineProposal(l));for(const d of symbolDetections){if(!d.symbolId||!d.bbox)continue;const point={x:d.bbox.x+d.bbox.width/2,y:d.bbox.y+d.bbox.height/2};s=addProposal(s,symbolProposal({id:`SYM-${d.id}`,symbolId:d.symbolId,point,bbox:d.bbox,confidence:d.confidence,sourceDetectionId:d.id}))}return{...s,policy:{autoConfirmThreshold:threshold}}}
export function reconstructionSummary(s){return{proposals:s.proposals.length,confirmed:s.proposals.filter(p=>p.status==='CONFIRMED').length,rejected:s.proposals.filter(p=>p.status==='REJECTED').length,pending:s.proposals.filter(p=>p.status==='PROPOSED').length,nativeEntities:s.entities.length,runs:Object.keys(s.graph.runs).length}}
