export const REFERENCE_TYPES=['application/pdf','image/png','image/jpeg','image/webp','image/svg+xml'];
export const TRACE_MODES=['off','trace','compare'];
const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)));
export function validateReferenceFile(file){const type=(file?.type||'').toLowerCase(),name=(file?.name||'').toLowerCase();const ext=name.split('.').pop();const allowed=REFERENCE_TYPES.includes(type)||['pdf','png','jpg','jpeg','webp','svg'].includes(ext);return{valid:allowed,type:type||({pdf:'application/pdf',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',svg:'image/svg+xml'}[ext]||''),reason:allowed?'':'Formato não suportado'}}
export function sanitizeSvg(svg=''){let s=String(svg);s=s.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,'').replace(/<foreignObject\b[^>]*>[\s\S]*?<\/foreignObject\s*>/gi,'').replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi,'').replace(/\s(?:href|xlink:href)\s*=\s*(["'])\s*(?:javascript:|data:text\/html)[\s\S]*?\1/gi,'');return s}
export function svgDataUrl(svg){return`data:image/svg+xml;charset=utf-8,${encodeURIComponent(sanitizeSvg(svg))}`}
export function createUnderlay(id,o={}){return{id,kind:'underlay',name:o.name||id,mimeType:o.mimeType||'',source:o.source||'',page:Number(o.page)||1,pageCount:Number(o.pageCount)||1,x:Number(o.x)||0,y:Number(o.y)||0,width:Math.max(1,Number(o.width)||600),height:Math.max(1,Number(o.height)||400),scale:Math.max(.001,Number(o.scale)||1),rotation:Number(o.rotation)||0,opacity:clamp(o.opacity??.45,0,1),locked:o.locked??true,visible:o.visible??true,crop:normalizeCrop(o.crop),layerName:'Imagem de referência',vectorInfo:o.vectorInfo||null,createdAt:o.createdAt||new Date().toISOString()}}
export function normalizeCrop(c){if(!c)return{x:0,y:0,width:1,height:1};const x=clamp(c.x??0,0,1),y=clamp(c.y??0,0,1);return{x,y,width:clamp(c.width??1,.001,1-x),height:clamp(c.height??1,.001,1-y)}}
export function updateUnderlay(u,patch={}){const n={...u,...patch};n.opacity=clamp(n.opacity,0,1);n.scale=Math.max(.001,Number(n.scale)||1);n.rotation=Number(n.rotation)||0;n.crop=normalizeCrop(n.crop);n.layerName='Imagem de referência';return n}
export function underlayBounds(u){const c=normalizeCrop(u.crop),w=u.width*u.scale*c.width,h=u.height*u.scale*c.height;return{x:u.x,y:u.y,width:w,height:h}}
export function createTraceState(o={}){return{mode:TRACE_MODES.includes(o.mode)?o.mode:'off',underlayId:o.underlayId||null,underlayLocked:o.underlayLocked??true,opacity:clamp(o.opacity??.35,0,1),snapIndependent:o.snapIndependent??true,hideOriginal:o.hideOriginal??false,comparison:o.comparison||'overlay'}}
export function updateTraceState(s,patch={}){const n={...s,...patch};n.mode=TRACE_MODES.includes(n.mode)?n.mode:'off';n.opacity=clamp(n.opacity,0,1);return n}
export function effectiveUnderlay(u,trace){if(!u)return null;const active=trace?.underlayId===u.id&&trace.mode!=='off';return{...u,locked:active?true:u.locked,opacity:active?trace.opacity:u.opacity,visible:active&&trace.hideOriginal?false:u.visible}}
export function inspectPdfVectorText(text=''){const s=String(text);const count=(re)=>(s.match(re)||[]).length;const paths=count(/\b(?:m|l|c|v|y|re|S|s|f|F|B|b)\b/g),texts=count(/\b(?:BT|Tj|TJ)\b/g),images=count(/\/Subtype\s*\/Image\b/g),pages=Math.max(1,count(/\/Type\s*\/Page\b/g));return{pdf:s.includes('%PDF'),pages,vectorOperators:paths,textOperators:texts,embeddedImages:images,predominantlyVector:paths>images*10&&paths>20}}
export function inspectSvgVector(svg=''){const clean=sanitizeSvg(svg);const tags=(re)=>(clean.match(re)||[]).length;return{vector:true,paths:tags(/<path\b/gi),lines:tags(/<line\b/gi),polylines:tags(/<polyline\b/gi),texts:tags(/<text\b/gi),sanitized:clean!==String(svg)}}
